interface Quote {
  text: string
  author: string
}

interface QuoteDatabase {
  [key: string]: Quote[]
}

// Quote database with inspirational and philosophical quotes
const quotes: QuoteDatabase = {
  en: [
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
    { text: "Yesterday is history, tomorrow is a mystery, today is a gift.", author: "Eleanor Roosevelt" },   { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "You learn more from failure than from success.", author: "Unknown" },
    {text: "If you are working on something exciting that you really care about, you don't have to be pushed.",author: "Steve Jobs",},
    {text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",author: "Winston Churchill",},
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    {text: "In this life we cannot do great things. We can only do small things with great love.",author: "Mother Teresa", },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    {text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",author: "Winston Churchill" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    {text: "The only person you are destined to become is the person you decide to be.",author: "Ralph Waldo Emerson",},
    {text: "Go confidently in the direction of your dreams. Live the life you have imagined.",author: "Henry David Thoreau",},
    {text: "When I was 5 years old, my mother always told me that happiness was the key to life.",author: "John Lennon", },
    { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    {text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",author: "Ralph Waldo Emerson",},
    {text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",author: "Nelson Mandela"},
    { text: "The future belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    {text: "What you get by achieving your goals is not as important as what you become by achieving your goals.",author: "Zig Ziglar",},
{text: "The only limit to our realization of tomorrow will be our doubts of today.",author: "Franklin D. Roosevelt",},
{ text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
{ text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
{ text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
{ text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
{ text: "The only way out is through.", author: "Robert Frost" },
{ text: "It is never too late to be what you might have been.", author: "George Eliot" },
{ text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
{ text: "The unexamined life is not worth living.", author: "Socrates (essential inclusion)" },
{ text: "Man is born free, and everywhere he is in chains.", author: "Jean-Jacques Rousseau" },
{ text: "Hell is other people.", author: "Jean-Paul Sartre" },
{ text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
{ text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
{ text: "We are all sentenced to solitary confinement inside our own skins, for life.", author: "Tennessee Williams" },
{ text: "Hell is a place where nothing connects with nothing.", author: "T.S. Eliot" },
{ text: "The stars are dead. The animals will not look. We are left alone with our day.", author: "W.H. Auden" },
{ text: "I have measured out my life with coffee spoons.", author: "T.S. Eliot" },
{ text: "The universe is a cruel, uncaring void. The key to being happy isn't to search for meaning. It's to keep yourself busy with unimportant nonsense, and eventually, you'll be dead.", author: "Mr. Peanutbutter (BoJack Horseman)" },
{ text: "I was never really insane except upon occasions when my heart was touched.", author: "Edgar Allan Poe" },
{ text: "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.", author: "H.P. Lovecraft" },
{ text: "There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.", author: "Bram Stoker" },
{ text: "We are each our own devil, and we make this world our hell.", author: "Oscar Wilde" },
{ text: "I have love in me the likes of which you can scarcely imagine and rage the likes of which you would not believe. If I cannot satisfy the one, I will indulge the other.", author: "Mary Shelley" },
{ text: "Life is a fleeting dream, and death the awakening.", author: "Murasaki Shikibu" },
{ text: "The blade itself incites to deeds of violence.", author: "Homer" },
{ text: "Autumn moonlight— a worm digs silently into the chestnut.", author: "Matsuo Bashō" },
{ text: "All human unhappiness comes from not facing reality squarely, exactly as it is.", author: "Yukio Mishima" },
{ text: "The world is a hellish place, and bad writing is destroying the quality of our suffering.", author: "Tom Waits" },
{ text: "Beware that, when fighting monsters, you yourself do not become a monster... for when you gaze long into the abyss, the abyss gazes also into you.", author: "Friedrich Nietzsche" },
{ text: "Is life not a thousand times too short for us to bore ourselves?", author: "Friedrich Nietzsche" },
{ text: "The thought of suicide is a great consolation: by means of it one gets through many a dark night.", author: "Friedrich Nietzsche" },
{ text: "Nothing is true, everything is permitted.", author: "Hassan-i Sabbah" },
{ text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
{ text: "You are not a drop in the ocean. You are the entire ocean in a drop.", author: "Rumi" },
{ text: "What you seek is seeking you.", author: "Rumi" },
{ text: "Be like a tree and let the dead leaves drop.", author: "Rumi" },
{ text: "The wound is the place where the Light enters you.", author: "Rumi" },
{ text: "Live life as if everything is rigged in your favor.", author: "Rumi" },
{ text: "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", author: "Heraclitus" },
{ text: "Happiness depends upon ourselves.", author: "Aristotle (included as essential)" },
{ text: "The measure of a man is what he does with power.", author: "Plato" },
{ text: "He who is not contented with what he has, would not be contented with what he would like to have.", author: "Democritus" },
{ text: "Know thyself.", author: "Inscription at Delphi (often attributed to Thales)" },
{ text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
{ text: "You must have chaos within you to give birth to a dancing star.", author: "Friedrich Nietzsche" },
{ text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
{ text: "Man is a mystery. It needs to be unravelled, and if you spend your whole life unravelling it, don't say that you've wasted time.", author: "Fyodor Dostoevsky" },
{ text: "Only people who are capable of loving strongly can also suffer great sorrow.", author: "Leo Tolstoy" },
{ text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin (Russian-born)" },
{ text: "The darker the night, the brighter the stars.", author: "Fyodor Dostoevsky" },
{ text: "If you look for perfection, you'll never be content.", author: "Leo Tolstoy" },
{ text: "In the midst of winter, I found there was, within me, an invincible summer.", author: "Albert Camus" },
{ text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", author: "Albert Camus" },
{ text: "Should I kill myself, or have a cup of coffee?", author: "Albert Camus" },
{ text: "Blessed are the hearts that can bend; they shall never be broken.", author: "Albert Camus" },
{ text: "You will never be happy if you continue to search for what happiness consists of.", author: "Albert Camus" },
{ text: "What's coming will come and we'll meet it when it does.", author: "J.K. Rowling (via Hedwig's Theme)" },
{ text: "All you touch and all you see is all your life will ever be.", author: "Pink Floyd (Breathe)" },
{ text: "The opposite of love's indifference.", author: "Lana Del Rey (Hope Is a Dangerous Thing)" },
{ text: "Maybe we're all just prisoners of our own device.", author: "Eagles (Hotel California)" },
{ text: "You can check out any time you like, but you can never leave.", author: "Eagles (Hotel California)" },
{ text: "Happiness does not depend on outward things, but on the way we see them.", author: "Leo Tolstoy" },
{ text: "To go wrong in one's own way is better than to go right in someone else's.", author: "Fyodor Dostoevsky" },
{ text: "If you want to be happy, be.", author: "Leo Tolstoy" },
{ text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author: "Fyodor Dostoevsky" },
{ text: "We can know only that we know nothing. And that is the highest degree of human wisdom.", author: "Leo Tolstoy" },
{ text: "The darker the night, the brighter the stars, the deeper the grief, the closer is God!", author: "Fyodor Dostoevsky" },
{ text: "Man is a mystery. It needs to be unravelled, and if you spend your whole life unravelling it, don't say that you've wasted time.", author: "Fyodor Dostoevsky" },
{ text: "I say let the world go to hell, but I should always have my tea.", author: "Fyodor Dostoevsky" },
{ text: "We sometimes encounter people, even perfect strangers, who begin to interest us at first sight, somehow suddenly, all at once, before a word has been spoken.", author: "Fyodor Dostoevsky" },
{ text: "To live without Hope is to Cease to live.", author: "Fyodor Dostoevsky" },
{ text: "He allowed himself to be swayed by his conviction that human beings are not born once and for all on the day their mothers give birth to them, but that life obliges them over and over again to give birth to themselves.", author: "Gabriel García Márquez" },
{ text: "I am not sure that I exist, actually. I am all the writers that I have read, all the people that I have met, all the women that I have loved; all the cities I have visited.", author: "Jorge Luis Borges" },
{ text: "Death is a dignitary who when he comes announced is to be received with formal manifestations of respect, even by those most familiar with him.", author: "Ambrose Bierce" },
{ text: "The world is a fine place and worth the fighting for and I hate very much to leave it.", author: "Ernest Hemingway" },
{ text: "We read to know we're not alone.", author: "C.S. Lewis" },
{ text: "You forget what you want to remember, and you remember what you want to forget.", author: "Cormac McCarthy" },
{ text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
{ text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
{ text: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung" },
{ text: "An unexamined life is not worth living.", author: "Socrates" },
{ text: "Until the lions have their own historians, the history of the hunt will always glorify the hunter.", author: "Chinua Achebe" },
{ text: "The child who is not embraced by the village will burn it down to feel its warmth.", author: "African Proverb" },
{ text: "To be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", author: "Nelson Mandela" },
{ text: "Until the lions have their own historians, the history of the hunt will always glorify the hunter.", author: "Chinua Achebe" },
{ text: "The child who is not embraced by the village will burn it down to feel its warmth.", author: "African Proverb" },
{ text: "To be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", author: "Nelson Mandela" },
{ text: "What matters in life is not what happens to you but what you remember and how you remember it.", author: "Gabriel García Márquez" },
{ text: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell" },
{ text: "I am my own muse. I am the subject I know best.", author: "Frida Kahlo" },
{ text: "Your pain is the breaking of the shell that encloses your understanding.", author: "Kahlil Gibran" },
{ text: "A pearl is a beautiful thing that is produced by an injured life.", author: "Adonis" },
{ text: "The wound is the place where the Light enters you.", author: "Rumi" },
{ text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
{ text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
{ text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
{ text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
{ text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
{ text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
{ text: "Be like a tree and let the dead leaves drop.", author: "Rumi" },
{ text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
{ text: "Sell your cleverness and buy bewilderment.", author: "Rumi" },
{ text: "The wound is where the light enters you.", author: "Rumi" },
{ text: "What you seek is seeking you.", author: "Rumi" },
{ text: "Your pain is the breaking of the shell that encloses your understanding.", author: "Kahlil Gibran" },
{ text: "Tenderness and kindness are not signs of weakness but manifestations of strength.", author: "Kahlil Gibran" },
{ text: "Out of suffering have emerged the strongest souls.", author: "Kahlil Gibran" },
{ text: "The teacher who walks in the shadow of the temple must give of his wisdom.", author: "Kahlil Gibran" },
{ text: "Work is love made visible.", author: "Kahlil Gibran" },
{ text: "The ink of the scholar is more sacred than the blood of the martyr.", author: "Prophet Muhammad" },
{ text: "The worst prison is a closed heart.", author: "Imam Ali" },
{ text: "Knowledge enlivens the soul.", author: "Al-Ghazali" },
{ text: "The universe is a grand book whose pages are the atoms.", author: "Ibn Arabi" },
{ text: "He who knows himself knows his Lord.", author: "Islamic Proverb" },
{ text: "From the East, I bring the fire of the sun.", author: "Fairuz" },
{ text: "We are the voice of the voiceless.", author: "Marcel Khalife " },
{ text: "My homeland is not a suitcase, and I am no traveler.", author: "Majida El Roumi (Lebanese Singer)" },
  ],


  fr: [
    {text: "Il n'y a point de génie sans un grain de folie.", author: "Aristote" },
    { text: "La vie est un sommeil, l'amour en est le rêve.", author: "Alfred de Musset" },
    {text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",author: "Antoine de Saint-Exupéry",},
    { text: "L'enfer, c'est les autres.", author: "Jean-Paul Sartre" },
    { text: "Je pense, donc je suis.", author: "René Descartes" },
    { text: "La liberté, c'est la liberté de dire que deux et deux font quatre.", author: "George Orwell" },
    { text: "Il faut cultiver notre jardin.", author: "Voltaire" },
    { text: "L'art de vivre consiste en un subtil mélange entre lâcher prise et tenir bon.", author: "Henri Lewis" },
    { text: "Le bonheur n'est pas une destination, c'est une façon de voyager.", author: "Margaret Lee Runbeck" },
    {text: "Celui qui déplace la montagne, c'est celui qui commence à enlever les petites pierres.",author: "Confucius",},
    { text: "La vraie générosité envers l'avenir consiste à tout donner au présent.", author: "Albert Camus" },
    { text: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.", author: "George Sand" },
    { text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" },
    {text: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",author: "Albert Einstein",},
    {text: "Le courage n'est pas l'absence de peur, mais la capacité de vaincre ce qui fait peur.", author: "Nelson Mandela",},
    { text: "Il vaut mieux faire que dire, il vaut mieux agir que se plaindre.", author: "Winston Churchill" },
    { text: "La seule façon de faire du bon travail, c'est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
    { text: "Ce n'est pas la montagne que nous conquérons, mais nous-mêmes.", author: "Sir Edmund Hillary" },
    {text: "La différence entre l'ordinaire et l'extraordinaire, c'est ce petit quelque chose en plus.",author: "Jimmy Johnson",},
    { text: "Le succès c'est d'aller d'échec en échec sans perdre son enthousiasme.", author: "Winston Churchill" },
    {text: "La plus grande révolution de notre génération est la découverte que l'être humain peut changer sa vie.",author: "William James"},
    { text: "Il n'est jamais trop tard pour être ce que vous auriez pu être.", author: "George Eliot" },
    { text: "La vie est trop importante pour être prise au sérieux.", author: "Oscar Wilde" },
    { text: "Soyez le changement que vous voulez voir dans le monde.", author: "Gandhi" },
    {text: "L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.", author: "Nelson Mandela"},
    {text: "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.",author: "Oscar Wilde"},
    { text: "Le temps est la chose la plus précieuse que nous puissions dépenser.", author: "Théophraste" },
    {text: "La sagesse, c'est d'avoir des rêves suffisamment grands pour ne pas les perdre de vue.",author: "Oscar Wilde",},
    { text: "Chaque expert était autrefois un débutant.", author: "Helen Hayes" },
    { text: "Le doute est le commencement de la sagesse.", author: "Aristote" },
    { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
   { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
    { text: "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui.",author: "Franklin D. Roosevelt",},
    { text: "Le meilleur moyen de prédire l'avenir est de le créer.", author: "Peter Drucker" },
    {text: "La vie est un cadeau, et elle nous offre le privilège, l'opportunité et la responsabilité de donner quelque chose en retour en devenant plus.",author: "Tony Robbins",},
    { text: "La sagesse commence dans l'émerveillement.", author: "Socrate" },
    { text: "Le bonheur est une habitude, cultivez-le.", author: "Elbert Hubbard" },
    { text: "La vie est un long apprentissage de la perte.", author: "Jean Cocteau" },
    { text: "Le but de la vie est de vivre, et de vivre pleinement.", author: "Jack London" },
    { text: "La beauté est dans les yeux de celui qui regarde.", author: "Margaret Wolfe Hungerford" },
    { text: "Le silence est d'or.", author: "Proverbe" },
    { text: "La patience est amère, mais son fruit est doux.", author: "Jean-Jacques Rousseau" },
    { text: "Le temps est un grand maître, dit-on, le malheur est qu'il tue ses élèves.", author: "Hector Berlioz" },
    { text: "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", author: "Mère Teresa" },
    {text: "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.",author: "Gandhi",},
    { text: "La vie est un art, il faut la peindre avec les couleurs de l'âme.", author: "Vincent Van Gogh" },
    { text: "Le bonheur est une fleur qu'il ne faut pas cueillir.", author: "André Gide" },
    { text: "La vie est un rêve, réveille-toi.", author: "Proverbe chinois" },
    { text: "Le savoir est une arme.", author: "Francis Bacon" },
    { text: "La vérité est une, mais les chemins pour y arriver sont multiples.", author: "Gandhi" },
    { text: "Le doute est le commencement de la sagesse.", author: "Aristote" },
    { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
    {text: "Le bonheur est souvent la seule chose que l'on puisse donner sans l'avoir et c'est en le donnant qu'on l'acquiert.",author: "Voltaire",},
    { text: "La seule façon de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès.", author: "Albert Schweitzer" },
    { text: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
    {text: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.",author: "Albert Einstein",},
    { text: "Le monde est un livre et ceux qui ne voyagent pas n'en lisent qu'une page.", author: "Saint Augustin" },
    { text: "La vie est une aventure audacieuse ou rien du tout.", author: "Helen Keller" },
    {text: "Le plus grand plaisir dans la vie est de faire ce que les gens disent que vous ne pouvez pas faire.",author: "Walter Bagehot",},
    { text: "La persévérance est la clé du succès.", author: "Confucius" },
    { text: "Le bonheur est une direction, pas une destination.", author: "Zig Ziglar" },
    { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
    {text: "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui.",author: "Franklin D. Roosevelt",},
    { text: "Le meilleur moyen de prédire l'avenir est de le créer.", author: "Peter Drucker" },
    {text: "La vie est un cadeau, et elle nous offre le privilège, l'opportunité et la responsabilité de donner quelque chose en retour en devenant plus.",author: "Tony Robbins",},
    { text: "La sagesse commence dans l'émerveillement.", author: "Socrate" },
    { text: "Le bonheur est une habitude, cultivez-le.", author: "Elbert Hubbard" },
    { text: "La vie est un long apprentissage de la perte.", author: "Jean Cocteau" },
    { text: "Le but de la vie est de vivre, et de vivre pleinement.", author: "Jack London" },
    { text: "La beauté est dans les yeux de celui qui regarde.", author: "Margaret Wolfe Hungerford" },
    { text: "Le silence est d'or.", author: "Proverbe" },
    { text: "La patience est amère, mais son fruit est doux.", author: "Jean-Jacques Rousseau" },
    { text: "Le temps est un grand maître, dit-on, le malheur est qu'il tue ses élèves.", author: "Hector Berlioz" },
    { text: "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", author: "Mère Teresa" },
    { text: "La vie est un art, il faut la peindre avec les couleurs de l'âme.", author: "Vincent Van Gogh" },
    { text: "Le bonheur est une fleur qu'il ne faut pas cueillir.", author: "André Gide" },
    { text: "La vie est un rêve, réveille-toi.", author: "Proverbe chinois" },
    { text: "Le savoir est une arme.", author: "Francis Bacon" },
    { text: "La vérité est une, mais les chemins pour y arriver sont multiples.", author: "Gandhi" },
    { text: "La mélancolie, c'est le bonheur d'être triste.", author: "Victor Hugo" },  
{ text: "L'avenir, c'est l'ombre que le présent projette sur l'avenir.", author: "Victor Hugo" },  
{ text: "La musique exprime ce qui ne peut être dit et sur quoi il est impossible de taire.", author: "Victor Hugo" },  
{ text: "La vie est une fleur dont l'amour est le miel.", author: "Victor Hugo" },  
{ text: "La liberté commence où l'ignorance finit.", author: "Victor Hugo" },  
{ text: "Au milieu de l'hiver, j'ai découvert en moi un invincible été.", author: "Albert Camus" },  
{ text: "L'absurde naît de cette confrontation entre l'appel humain et le silence déraisonnable du monde.", author: "Albert Camus" },  
{ text: "Il n'y a pas de honte à préférer le bonheur.", author: "Albert Camus" },  
{ text: "La vérité, comme la lumière, aveugle.", author: "Albert Camus" },  
{ text: "Créer, c'est vivre deux fois.", author: "Albert Camus" },  
{ text: "On ne guérit jamais d'une enfance blessée.", author: "Yasmina Khadra" },  
{ text: "L'espoir est la seule chose qui nous reste quand tout est perdu.", author: "Yasmina Khadra" },  
{ text: "La peur est une prison où l'on s'enferme soi-même.", author: "Yasmina Khadra" },  
{ text: "L'amour est le seul luxe qui ne coûte rien.", author: "Yasmina Khadra" },  
{ text: "La vie est un roman dont nous sommes à la fois l'auteur et le personnage.", author: "Yasmina Khadra" },  
{ text: "Si vous demandez ce que je viens faire en ce monde, je vous répondrai : je viens vivre tout haut.", author: "Émile Zola" },  
{ text: "La vérité est en marche, et rien ne l'arrêtera.", author: "Émile Zola" },  
{ text: "L'art est un coin de la création vu à travers un tempérament.", author: "Émile Zola" },  
{ text: "On ne peut pas vivre sans amour, sans passion, sans quelque folie.", author: "Émile Zola" },  
{ text: "Le bonheur n'est que dans la réalisation de soi.", author: "Émile Zola" },  
{ text: "Je pense, donc je suis.", author: "René Descartes" },  
{ text: "Le bon sens est la chose du monde la mieux partagée.", author: "René Descartes" },  
{ text: "Douter de tout ou tout croire, ce sont deux solutions également commodes.", author: "René Descartes" },  
{ text: "La lecture de tous les bons livres est comme une conversation avec les plus honnêtes gens des siècles passés.", author: "René Descartes" },  
{ text: "L'âme est plus facile à connaître que le corps.", author: "René Descartes" },  
{ text: "La douleur est un lieu obscur où l'on apprend à voir.", author: "Marguerite Yourcenar" },  
{ text: "Le vrai lieu de naissance est celui où l'on a porté pour la première fois un regard intelligent sur soi-même.", author: "Marguerite Yourcenar" },  
{ text: "La vie est un sommeil, l'amour en est le rêve.", author: "Marguerite Yourcenar" },  
{ text: "La liberté n'est pas un don, mais une conquête.", author: "Marguerite Yourcenar" },  
{ text: "On ne possède que ce que l'on donne.", author: "Marguerite Yourcenar" },  
{ text: "La musique souvent me prend comme une mer.", author: "Charles Baudelaire" },  
{ text: "Le beau est toujours bizarre.", author: "Charles Baudelaire" },  
{ text: "La plus belle des ruses du diable est de vous persuader qu'il n'existe pas.", author: "Charles Baudelaire" },  
{ text: "La volupté unique et suprême de l'amour gît dans la certitude de faire le mal.", author: "Charles Baudelaire" },  
{ text: "Je suis un cimetière abhorré de la lune.", author: "Charles Baudelaire" },  
{ text: "On ne naît pas femme, on le devient.", author: "Simone de Beauvoir" },  
{ text: "La liberté, c'est de pouvoir choisir sa propre vie.", author: "Simone de Beauvoir" },  
{ text: "Rien n'est plus dangereux que la certitude d'avoir raison.", author: "Simone de Beauvoir" },  
{ text: "La vieillesse est un naufrage.", author: "Simone de Beauvoir" },  
{ text: "L'écriture est une façon de dire non à la mort.", author: "Simone de Beauvoir" },  
{ text: "Le silence est le cri le plus puissant.", author: "Anonyme" },  
{ text: "L'amour est la seule folie qui justifie la vie.", author: "Anonyme" },  
{ text: "Chaque larme est une histoire non racontée.", author: "Anonyme" },  
{ text: "La solitude est le miroir où l'âme se regarde.", author: "Anonyme" },  
{ text: "La vie n'est qu'une ombre qui passe, mais l'amour est la lumière qui demeure.", author: "Anonyme" },  
{ text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", author: "Antoine de Saint-Exupéry" },
{ text: "Tu deviens responsable pour toujours de ce que tu as apprivoisé.", author: "Antoine de Saint-Exupéry" },
{ text: "Toutes les grandes personnes ont d'abord été des enfants, mais peu d'entre elles s'en souviennent.", author: "Antoine de Saint-Exupéry" },
{ text: "Si Dieu n'existe pas, tout est permis.", author: "Fiodor Dostoïevski" },
{ text: "L'amour, c'est la vie. Tout, tout s'explique par l'amour.", author: "Léon Tolstoï" },
{ text: "Les larmes sont des mots que le cœur ne peut exprimer.", author: "Anton Tchekhov" },
{ text: "L'enfer, c'est les autres.", author: "Jean-Paul Sartre" },
{ text: "Il n'y a qu'un problème philosophique vraiment sérieux : c'est le suicide.", author: "Albert Camus" },
{ text: "La brièveté est la sœur du talent.", author: "Anton Tchekhov" },
{ text: "Les hommes vivent comme ils boivent. Certains versent la vie sur eux-mêmes, d'autres y trempent à peine leurs lèvres.", author: "Anton Tchekhov" },
{ text: "Tout savoir, c'est tout pardonner.", author: "Anton Tchekhov" },
{ text: "La poésie naît de l'ordure et des larmes.", author: "Anna Akhmatova" },
{ text: "Si tous les cœurs souffrants étaient retirés de la terre, elle cesserait de tourner.", author: "Anna Akhmatova" },
{ text: "Je n'ai pas besoin de beaucoup de mots, j'ai besoin d'un seul : vérité.", author: "Anna Akhmatova" },
{ text: "L'homme est condamné à être libre.", author: "Jean-Paul Sartre" },
{ text: "La mélancolie, c'est le bonheur d'être triste.", author: "Victor Hugo" },
{ text: "Nous sommes tous dans le caniveau, mais certains d'entre nous regardent les étoiles.", author: "Oscar Wilde" },
{ text: "La mort est une amie qui nous visite une seule fois.", author: "Gustave Flaubert" },
{ text: "La vie n'est pas ce que l'on a vécu, mais ce dont on se souvient et comment on s'en souvient.", author: "Gabriel García Márquez" },
{ text: "L'amour est une force plus impressionnante que la mort.", author: "Isabel Allende" },
{ text: "La réalité n'est pas toujours la plus probable ou la plus logique.", author: "Jorge Luis Borges" },
{ text: "Ce qui ne me tue pas me rend plus fort.", author: "Friedrich Nietzsche" },
{ text: "Il faut avoir encore du chaos en soi pour accoucher d'une étoile dansante.", author: "Friedrich Nietzsche" },
{ text: "Je est un autre.", author: "Arthur Rimbaud" },
{ text: "La nuit est une mer, les étoiles sont ses vagues.", author: "Mahmoud Darwich" },
{ text: "Tout meurt, même la mort elle-même.", author: "Victor Hugo" },
{ text: "Aimer, c'est souffrir et il n'y a pas d'amour sans souffrance.", author: "Fiodor Dostoïevski" },
{ text: "La beauté sauvera le monde.", author: "Fiodor Dostoïevski" },
{ text: "Nous sommes tous responsables de tout et de tous devant tous.", author: "Fiodor Dostoïevski" },

  ],
  it: [
    { text: "La semplicità è l'ultima sofisticazione.", author: "Leonardo da Vinci" },
    { text: "Chi non risica, non rosica.", author: "Proverbio italiano" },
    {text: "L'arte dice l'indicibile; esprime l'inesprimibile, traduce l'intraducibile.",author: "Leonardo da Vinci",},
    {text: "Non si può insegnare niente a un uomo; si può solo aiutarlo a trovare la risposta dentro di sé.",author: "Galileo Galilei",},
{ text: "L'amor che move il sole e l'altre stelle.", author: "Dante Alighieri" },
{ text: "Considerate la vostra semenza: fatti non foste a viver come bruti...", author: "Dante Alighieri" },
{ text: "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.", author: "Dante Alighieri" },
{ text: "Sei una notte oscura e sei anche la luna che la illumina.", author: "Rumi" },
{ text: "Dove c'è luce c'è anche ombra. Non cercare solo una delle due.", author: "Rumi" },
{ text: "La ferita è il luogo da cui entra la luce.", author: "Rumi" },
{ text: "Se Dio non esiste, tutto è permesso.", author: "Fëdor Dostoevskij" },
{ text: "Le famiglie felici sono tutte simili; ogni famiglia infelice è infelice a modo suo.", author: "Lev Tolstoj" },
{ text: "La brevità è sorella del talento.", author: "Anton Čechov" },
{ text: "Quando vuoi una cosa, tutto l'universo cospira affinché tu la realizzi.", author: "Paulo Coelho" },
{ text: "Solo una cosa rende impossibile un sogno: la paura di fallire.", author: "Paulo Coelho" },
{ text: "Il mondo cambia con il tuo esempio, non con la tua opinione.", author: "Paulo Coelho" },
{ text: "La terra ci stringe fino a farci diventare poesia.", author: "Mahmoud Darwish" },
{ text: "Se solo fossi un sasso sul pendio, forse sarei felice.", author: "Mahmoud Darwish" },
{ text: "Scrivo perché conosco la fine in anticipo.", author: "Mahmoud Darwish" },
{ text: "Il sonno della ragione genera mostri.", author: "Francisco Goya" },
{ text: "Vivi come se dovessi morire domani. Impara come se dovessi vivere per sempre.", author: "Mahatma Gandhi" },
{ text: "La vita è ciò che ti accade mentre sei occupato a fare altri progetti.", author: "John Lennon" },
{ text: "La libertà è come l'aria: ci si accorge di quanto vale quando comincia a mancare.", author: "Piero Calamandrei" },
{ text: "Credo che nel mondo esista una sola bellezza: quella della verità.", author: "Giordano Bruno" },
{ text: "La storia è una galera che va sempre avanti.", author: "Leonardo Sciascia" },
{ text: "E il naufragar m'è dolce in questo mare.", author: "Giacomo Leopardi" },
{ text: "La vita è un brivido che vola via.", author: "Luigi Pirandello" },
{ text: "Verrà la morte e avrà i tuoi occhi.", author: "Cesare Pavese" },
{ text: "La solitudine è il prezzo della libertà.", author: "Oriana Fallaci" },
{ text: "Siamo fatti della stessa sostanza dei sogni.", author: "William Shakespeare" },
{ text: "La paura è la più grande prigione dell'uomo.", author: "Nelson Mandela" },
{ text: "L'inferno sono gli altri.", author: "Jean-Paul Sartre" },
{ text: "Tutto ciò che siamo è il risultato di ciò che abbiamo pensato.", author: "Buddha" },
{ text: "La verità vi farà liberi.", author: "Vangelo di Giovanni" },
{ text: "Siamo eroi solo per una notte.", author: "David Bowie (Heroes)" },
{ text: "Tutto ciò che luccica non è oro.", author: "Shakespeare/Canzone popolare" },
{ text: "L'amore è cieco, ma il cuore vede tutto.", author: "Proverbio/Canzone" },
{ text: "La disperazione è il prezzo che si paga per aver sperato troppo.", author: "Eugenio Montale" },
{ text: "Non esiste vento favorevole per il marinaio che non sa dove andare.", author: "Seneca" },
{ text: "La bellezza salverà il mondo.", author: "Fëdor Dostoevskij" },
{ text: "Scrivo per capire, non per essere capito.", author: "Elias Canetti" },
{ text: "L'arte è una menzogna che ci avvicina alla verità.", author: "Pablo Picasso" },
{ text: "La pazzia è fare sempre la stessa cosa aspettandosi risultati diversi.", author: "Albert Einstein" },
    { text: "Il tempo è la cosa più preziosa che possiamo spendere.", author: "Teofrasto" },
    { text: "Chi ha pazienza può ottenere ciò che vuole.", author: "Benjamin Franklin" },
    { text: "La felicità non è avere quello che si desidera, ma desiderare quello che si ha.", author: "Oscar Wilde" },
    { text: "Ogni grande viaggio inizia con un piccolo passo.", author: "Lao Tzu" },
    {text: "La cultura è l'unico bene dell'umanità che, diviso fra tutti, anziché diminuire diventa più grande.",author: "Hans Georg Gadamer",},
    { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
    { text: "Non è mai troppo tardi per essere quello che avresti potuto essere.", author: "George Eliot" },
    { text: "La vita è troppo importante per essere presa sul serio.", author: "Oscar Wilde" },
    { text: "L'immaginazione è più importante della conoscenza.", author: "Albert Einstein" },
    {text: "Il coraggio non è l'assenza di paura, ma la capacità di vincere ciò che fa paura.",author: "Nelson Mandela",},
    { text: "È meglio fare che dire, è meglio agire che lamentarsi.", author: "Winston Churchill" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "Non è la montagna che conquistiamo, ma noi stessi.", author: "Sir Edmund Hillary" },
    {text: "La differenza tra l'ordinario e lo straordinario è quel piccolo qualcosa in più.",author: "Jimmy Johnson",},
    {text: "Il successo è andare di fallimento in fallimento senza perdere l'entusiasmo.",author: "Winston Churchill",},
    {text: "La più grande rivoluzione della nostra generazione è la scoperta che l'essere umano può cambiare la sua vita.",author: "William James"},
    { text: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Gandhi" },
    { text: "L'educazione è l'arma più potente che puoi usare per cambiare il mondo.", author: "Nelson Mandela" },
    { text: "Bisogna sempre puntare alla luna, perché anche se sbagli, atterri tra le stelle.", author: "Oscar Wilde" },
    { text: "La saggezza è avere sogni abbastanza grandi da non perderli di vista.", author: "Oscar Wilde" },
    { text: "Ogni esperto è stato una volta un principiante.", author: "Helen Hayes" },
    { text: "Il dubbio è l'inizio della saggezza.", author: "Aristotele" },
    { text: "La vita è un mistero da vivere, non un problema da risolvere.", author: "Gandhi" },
    {text: "La felicità è spesso l'unica cosa che si può dare senza averla, ed è dandola che la si acquista.",author: "Voltaire", },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    {text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.",author: "Albert Schweitzer", },
    { text: "La semplicità è la massima sofisticazione.", author: "Leonardo da Vinci" },
    {text: "La conoscenza si acquisisce con l'esperienza, tutto il resto è solo informazione.",author: "Albert Einstein"},
    { text: "Il mondo è un libro e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "La vita è un'avventura audace o niente affatto.", author: "Helen Keller" },
    {text: "Il più grande piacere della vita è fare ciò che la gente dice che non puoi fare.",author: "Walter Bagehot",},
    { text: "La perseveranza è la chiave del successo.", author: "Confucio" },
    { text: "La felicità è una direzione, non una destinazione.", author: "Zig Ziglar" },
    {text: "La vita è breve, rompi le regole, perdona in fretta, bacia lentamente, ama veramente, ridi senza controllo e non rimpiangere mai nulla che ti abbia fatto sorridere.",author: "Mark Twain",},
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    {text: "L'unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi.",author: "Franklin D. Roosevelt",},
    { text: "Il modo migliore per prevedere il futuro è crearlo.", author: "Peter Drucker" },
    {text: "La vita è un dono, e ci offre il privilegio, l'opportunità e la responsabilità di restituire qualcosa diventando di più.",author: "Tony Robbins",},
    { text: "La saggezza inizia nella meraviglia.", author: "Socrate" },
    { text: "La felicità è un'abitudine, coltivala.", author: "Elbert Hubbard" },
    { text: "La vita è un lungo apprendimento della perdita.", author: "Jean Cocteau" },
    { text: "Lo scopo della vita è vivere, e vivere pienamente.", author: "Jack London" },
    { text: "La bellezza è negli occhi di chi guarda.", author: "Margaret Wolfe Hungerford" },
    { text: "Il silenzio è d'oro.", author: "Proverbio" },
    { text: "La pazienza è amara, ma il suo frutto è dolce.", author: "Jean-Jacques Rousseau" },
    { text: "Il tempo è un grande maestro, si dice, il guaio è che uccide i suoi allievi.", author: "Hector Berlioz" },
    {text: "La vita è una sfida da affrontare, una felicità da meritare, un'avventura da tentare.",author: "Madre Teresa",},
    {text: "Il più grande viaggiatore non è colui che ha fatto dieci volte il giro del mondo, ma colui che ha fatto una sola volta il giro di se stesso.",author: "Gandhi", },
    { text: "La vita è un'arte, bisogna dipingerla con i colori dell'anima.", author: "Vincent Van Gogh" },
    { text: "La felicità è un fiore che non bisogna cogliere.", author: "André Gide" },
    { text: "La vita è un sogno, svegliati.", author: "Proverbio cinese" },
    { text: "La conoscenza è un'arma.", author: "Francis Bacon" },
    { text: "La verità è una, ma i sentieri per raggiungerla sono molteplici.", author: "Gandhi" },
    { text: "Il dubbio è l'inizio della saggezza.", author: "Aristotele" },
    { text: "La vita è un mistero da vivere, non un problema da risolvere.", author: "Gandhi" },
    {text: "La felicità è spesso l'unica cosa che si può dare senza averla, ed è dandola che la si acquista.",author: "Voltaire",},
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    {text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.", author: "Albert Schweitzer", },
    { text: "La semplicità è la massima sofisticazione.", author: "Leonardo da Vinci" },
    {text: "La conoscenza si acquisisce con l'esperienza, tutto il resto è solo informazione.", author: "Albert Einstein",},
    { text: "Il mondo è un libro e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "La vita è un'avventura audace o niente affatto.", author: "Helen Keller" },
    {text: "Il più grande piacere della vita è fare ciò che la gente dice che non puoi fare.",author: "Walter Bagehot",},
    { text: "La perseveranza è la chiave del successo.", author: "Confucio" },
    { text: "La felicità è una direzione, non una destinazione.", author: "Zig Ziglar" },
    {text: "La vita è breve, rompi le regole, perdona in fretta, bacia lentamente, ama veramente, ridi senza controllo e non rimpiangere mai nulla che ti abbia fatto sorridere.",author: "Mark Twain",},
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    {text: "L'unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi.",author: "Franklin D. Roosevelt",},
    { text: "Il modo migliore per prevedere il futuro è crearlo.", author: "Peter Drucker" },
    {text: "La vita è un dono, e ci offre il privilegio, l'opportunità e la responsabilità di restituire qualcosa diventando di più.",author: "Tony Robbins", },
    { text: "La saggezza inizia nella meraviglia.", author: "Socrate" },
    { text: "La felicità è un'abitudine, coltivala.", author: "Elbert Hubbard" },
    { text: "La vita è un lungo apprendimento della perdita.", author: "Jean Cocteau" },
    { text: "Lo scopo della vita è vivere, e vivere pienamente.", author: "Jack London" },
    { text: "La bellezza è negli occhi di chi guarda.", author: "Margaret Wolfe Hungerford" },
    { text: "Il silenzio è d'oro.", author: "Proverbio" },
    { text: "La pazienza è amara, ma il suo frutto è dolce.", author: "Jean-Jacques Rousseau" },
    { text: "Il tempo è un grande maestro, si dice, il guaio è che uccide i suoi allievi.", author: "Hector Berlioz" },
    { text: "La vita è una sfida da affrontare, una felicità da meritare, un'avventura da tentare.", author: "Madre Teresa" },
    {text: "Il più grande viaggiatore non è colui che ha fatto dieci volte il giro del mondo, ma colui che ha fatto una sola volta il giro di se stesso.",author: "Gandhi",},
    { text: "La vita è un'arte, bisogna dipingerla con i colori dell'anima.", author: "Vincent Van Gogh" },
    { text: "La felicità è un fiore che non bisogna cogliere.", author: "André Gide" },
    { text: "La vita è un sogno, svegliati.", author: "Proverbio cinese" },
    { text: "La conoscenza è un'arma.", author: "Francis Bacon" },
    { text: "La verità è una, ma i sentieri per raggiungerla sono molteplici.", author: "Gandhi" },
    { text: "L'amor che move il sole e l'altre stelle.", author: "Dante Alighieri" },  
{ text: "Lasciate ogne speranza, voi ch'intrate.", author: "Dante Alighieri" },  
{ text: "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.", author: "Dante Alighieri" },  
{ text: "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.", author: "Dante Alighieri" },  
{ text: "L’amore e ’l cor gentil sono una cosa.", author: "Dante Alighieri" },  
{ text: "Il naufragar m'è dolce in questo mare.", author: "Giacomo Leopardi" },  
{ text: "Sempre caro mi fu quest'ermo colle.", author: "Giacomo Leopardi" },  
{ text: "La vita è un brivido che scorre tra due nulla.", author: "Giacomo Leopardi" },  
{ text: "Il mondo è un nulla, e l’uomo è un’ombra.", author: "Giacomo Leopardi" },  
{ text: "Tutto è male, e il meglio è non essere.", author: "Giacomo Leopardi" },  
{ text: "Così è (se vi pare).", author: "Luigi Pirandello" },  
{ text: "Uno, nessuno e centomila.", author: "Luigi Pirandello" },  
{ text: "La follia è l’unico modo per sopravvivere alla realtà.", author: "Luigi Pirandello" },  
{ text: "La verità è figlia del tempo, non dell’autorità.", author: "Luigi Pirandello" },  
{ text: "Ognuno di noi ha dentro di sé un intero mondo sconosciuto.", author: "Luigi Pirandello" },  
{ text: "Spesso il male di vivere ho incontrato.", author: "Eugenio Montale" },  
{ text: "Codesto solo oggi possiamo dirti: ciò che non siamo, ciò che non vogliamo.", author: "Eugenio Montale" },  
{ text: "La vita è questo scialo di triti fatti.", author: "Eugenio Montale" },  
{ text: "Forse un mattino andando in un’aria di vetro.", author: "Eugenio Montale" },  
{ text: "La speranza è l’ultima a morire, ma muore.", author: "Eugenio Montale" },  
{ text: "La solitudine è la mia compagna fedele.", author: "Umberto Saba" },  
{ text: "Amo la vita, anche se mi fa male.", author: "Umberto Saba" },  
{ text: "La poesia è un grido disperato di gioia.", author: "Umberto Saba" },  
{ text: "Nessuno sa di sé quel che sa l’anima.", author: "Umberto Saba" },  
{ text: "Il dolore è la mia patria.", author: "Umberto Saba" },  
{ text: "La follia è una condizione umana.", author: "Alda Merini" },  
{ text: "Sono nata il ventuno a primavera.", author: "Alda Merini" },  
{ text: "La poesia è la voce dell’anima.", author: "Alda Merini" },  
{ text: "Il dolore è il mio pane quotidiano.", author: "Alda Merini" },  
{ text: "L’amore è l’unica follia che vale la pena vivere.", author: "Alda Merini" },  
{ text: "L’universo è infinito, perché è la manifestazione di un Dio infinito.", author: "Giordano Bruno" },  
{ text: "La verità è figlia del tempo.", author: "Giordano Bruno" },  
{ text: "Non c’è nulla di più pericoloso di un’idea quando ne hai una sola.", author: "Giordano Bruno" },  
{ text: "L’anima non muore, ma si trasforma.", author: "Giordano Bruno" },  
{ text: "Chi cerca la verità deve dubitare di tutto.", author: "Giordano Bruno" },  
{ text: "Il silenzio è l’urlo più forte.", author: "Anonimo" },  
{ text: "Vivere è navigare in un mare di domande senza risposte.", author: "Anonimo" },  
{ text: "L’amore è l’unica luce che non teme l’oscurità.", author: "Anonimo" },  
{ text: "La morte non è la fine, ma solo un cambio di abito.", author: "Anonimo" },  
{ text: "Ogni lacrima è una poesia non scritta.", author: "Anonimo" },  
  ],


  es: [
    { text: "No hay camino para la paz, la paz es el camino.", author: "Gandhi" },
    { text: "La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.",author: "John Lennon",},
    { text: "Solo sé que no sé nada.", author: "Sócrates" },
    { text: "El que no arriesga no gana.", author: "Refrán español" },
    { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
    { text: "No dejes para mañana lo que puedas hacer hoy.", author: "Benjamin Franklin" },
    { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
    { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
    { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "La vida es 10% lo que te sucede y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
    { text: "El futuro pertenece a aquellos que creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
    { text: "Nunca es demasiado tarde para ser lo que podrías haber sido.", author: "George Eliot" },
    { text: "La vida es demasiado importante para tomarla en serio.", author: "Oscar Wilde" },
    {text: "El coraje no es la ausencia de miedo, sino la capacidad de vencer lo que da miedo.",author: "Nelson Mandela",},
    { text: "Es mejor hacer que decir, es mejor actuar que quejarse.", author: "Winston Churchill" },
    { text: "No es la montaña lo que conquistamos, sino a nosotros mismos.", author: "Sir Edmund Hillary" },
    { text: "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.", author: "Jimmy Johnson" },
    {text: "La mayor revolución de nuestra generación es el descubrimiento de que el ser humano puede cambiar su vida.",author: "William James",},
    { text: "Sé el cambio que quieres ver en el mundo.", author: "Gandhi" },
    { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
    {text: "Siempre apunta a la luna, porque incluso si fallas, aterrizarás entre las estrellas.", author: "Oscar Wilde",},
    {text: "La sabiduría es tener sueños lo suficientemente grandes como para no perderlos de vista.",author: "Oscar Wilde",},
    { text: "Todo experto fue una vez un principiante.", author: "Helen Hayes" },
    { text: "La mejor manera de empezar es dejar de hablar y empezar a hacer.", author: "Walt Disney" },
    { text: "No dejes que el ayer ocupe demasiado espacio del hoy.", author: "Will Rogers" },
    { text: "Aprendes más del fracaso que del éxito.", author: "Desconocido" },
    {text: "Si estás trabajando en algo emocionante que realmente te importa, no tienes que ser empujado.",author: "Steve Jobs", },
    {text: "El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta.",author: "Winston Churchill",},
    { text: "Es mejor fallar en originalidad que tener éxito en imitación.", author: "Herman Melville" },
    { text: "El camino al éxito y el camino al fracaso son casi exactamente el mismo.", author: "Colin R. Davis" },
    { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
    { text: "La vida es un misterio que hay que vivir, no un problema que resolver.", author: "Gandhi" },
    {text: "La felicidad es a menudo lo único que puedes dar sin tenerla, y es dándola como la adquieres.",author: "Voltaire", },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    {text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",author: "Albert Schweitzer",},
    { text: "En un lugar de la Mancha, de cuyo nombre no quiero acordarme...", author: "Miguel de Cervantes" },
{ text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes" },
{ text: "Vivir sin filosofar es, propiamente, tener los ojos cerrados.", author: "Santa Teresa de Jesús" },
{ text: "A donde hay música no puede haber cosa mala.", author: "Miguel de Cervantes" },
{ text: "Nada nos hace envejecer con más rapidez que el pensar incesantemente en que nos hacemos viejos.", author: "Gregorio Marañón" },
{ text: "Verde que te quiero verde.", author: "Federico García Lorca" },
{ text: "El más terrible de todos los sentimientos es el sentimiento de tener la esperanza muerta.", author: "Federico García Lorca" },
{ text: "Bajo el ala aleve del abanico.", author: "Luis Cernuda" },
{ text: "La poesía es el diálogo del hombre, de un hombre con su tiempo.", author: "Luis Cernuda" },
{ text: "Caminante, no hay camino, se hace camino al andar.", author: "Antonio Machado" },
{ text: "El amor es tan corto y el olvido es tan largo.", author: "Pablo Neruda" },
{ text: "Podrán cortar todas las flores, pero no podrán detener la primavera.", author: "Pablo Neruda" },
{ text: "La muerte es democrática, al fin y al cabo.", author: "Gabriel García Márquez" },
{ text: "Lo único que me duele de morir, es que no sea de amor.", author: "Gabriel García Márquez" },
{ text: "La vida no es la que uno vivió, sino la que uno recuerda.", author: "Gabriel García Márquez" },
{ text: "Pienso, luego existo.", author: "René Descartes" },
{ text: "El infierno son los otros.", author: "Jean-Paul Sartre" },
{ text: "La libertad es el derecho a decirle a la gente lo que no quiere oír.", author: "George Orwell" },
{ text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
{ text: "No hay caminos para la paz; la paz es el camino.", author: "Mahatma Gandhi" },
{ text: "Todos los hombres felices se parecen; cada hombre infeliz es infeliz a su manera.", author: "León Tolstói" },
{ text: "Si Dios no existe, todo está permitido.", author: "Fiódor Dostoyevski" },
{ text: "La belleza salvará al mundo.", author: "Fiódor Dostoyevski" },
{ text: "El hombre es un misterio. Hay que desentrañarlo.", author: "Fiódor Dostoyevski" },
{ text: "La primavera es el tiempo de los planes y proyectos.", author: "León Tolstói" },
{ text: "Ayer era listo, así que quería cambiar el mundo. Hoy soy sabio, así que me cambio a mí mismo.", author: "Rumi" },
{ text: "No eres una gota en el océano. Eres todo el océano en una gota.", author: "Rumi" },
{ text: "La herida es el lugar por donde entra la luz.", author: "Rumi" },
{ text: "Lo que buscas te está buscando.", author: "Rumi" },
{ text: "Vive como si todo estuviera conspirando a tu favor.", author: "Rumi" },
{ text: "El amor que mueve el sol y las demás estrellas.", author: "Dante Alighieri" },
{ text: "No hay mayor dolor que recordar los tiempos felices en la miseria.", author: "Dante Alighieri" },
{ text: "Abandonad toda esperanza, vosotros los que entráis.", author: "Dante Alighieri" },
{ text: "Considerad vuestro origen: no nacisteis para vivir como brutos.", author: "Dante Alighieri" },
{ text: "La naturaleza es el arte de Dios.", author: "Dante Alighieri" },
{ text: "Cuando quieres algo, todo el Universo conspira para que lo consigas.", author: "Paulo Coelho" },
{ text: "Sólo una cosa hace que un sueño sea imposible: el miedo al fracaso.", author: "Paulo Coelho" },
{ text: "El mundo cambia con tu ejemplo, no con tu opinión.", author: "Paulo Coelho" },
{ text: "El amor no es lo que la gente dice, es lo que la gente demuestra.", author: "Paulo Coelho" },
{ text: "La magia es creer en ti mismo.", author: "Paulo Coelho" },
{ text: "La vida es una tómbola, mi amor.", author: "Marisol (Canción)" },
{ text: "Que nadie calme tu locura.", author: "Joaquín Sabina" },
{ text: "Cada día es un viaje, y el viaje mismo es hogar.", author: "Jorge Drexler" },
{ text: "No dejes que termine el día sin que crezca un poco tu sueño.", author: "Silvio Rodríguez" },
{ text: "Lo pasado, pasado está.", author: "José José" },
{ text: "No llores porque ya se terminó, sonríe porque sucedió.", author: "Gabriel García Márquez" },
{ text: "El amor no tiene edad, siempre está naciendo.", author: "Gabriel García Márquez" },
{ text: "La sabiduría nos llega cuando ya no sirve para nada.", author: "Gabriel García Márquez" },
{ text: "Para mi corazón basta tu pecho, para tu libertad bastan mis alas.", author: "Pablo Neruda" },
{ text: "Puedo escribir los versos más tristes esta noche...", author: "Pablo Neruda" },
{ text: "El niño que no juega no es niño, pero el hombre que no juega perdió para siempre al niño que vivía en él.", author: "Pablo Neruda" },
{ text: "Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos.", author: "Julio Cortázar" },
{ text: "El verdadero amor es cuando dos soledades se protegen, se limitan y se saludan.", author: "Julio Cortázar" },
{ text: "Nada está perdido si se tiene el valor de proclamar que todo está perdido.", author: "Julio Cortázar" },
{ text: "El amor es un estado de perpetua insatisfacción.", author: "Octavio Paz" },
{ text: "La poesía es el encuentro del hombre con su soledad.", author: "Octavio Paz" },
{ text: "Sin democracia, la libertad es una quimera.", author: "Octavio Paz" },
{ text: "Cuando teníamos las respuestas, nos cambiaron las preguntas.", author: "Mario Benedetti" },
{ text: "El amor es un acto de valor, no de temor.", author: "Mario Benedetti" },
{ text: "No te rindas, por favor no cedas, aunque el frío queme.", author: "Mario Benedetti" },
{ text: "No gastes el tiempo intentando ser importante. Gástalo creando algo que lo sea.", author: "Isabel Allende" },
{ text: "El miedo es inevitable, yo lo tengo siempre, pero también tengo un coraje que no se rinde.", author: "Isabel Allende" },
{ text: "Escribe lo que no debe ser olvidado.", author: "Isabel Allende" },
{ text: "Siempre imaginé que el Paraíso sería algún tipo de biblioteca.", author: "Jorge Luis Borges" },
{ text: "Uno no es lo que es por lo que escribe, sino por lo que ha leído.", author: "Jorge Luis Borges" },
{ text: "El tiempo es el mejor antologista.", author: "Jorge Luis Borges" },
{ text: "La poesía no quiere adeptos, quiere amantes.", author: "Federico García Lorca" },
{ text: "El más terrible de todos los sentimientos es el sentimiento de tener la esperanza muerta.", author: "Federico García Lorca" },
{ text: "Como no me he preocupado de nacer, no me preocupo de morir.", author: "Federico García Lorca" },
{ text: "La fe que no duda es fe muerta.", author: "Miguel de Unamuno" },
{ text: "Solo el que sabe es libre, y más libre el que más sabe.", author: "Miguel de Unamuno" },
{ text: "El modo de dar una vez en el clavo es dar cien veces en la herradura.", author: "Miguel de Unamuno" },
{ text: "Yo tengo un miedo terrible de ser un alma en pena.", author: "Alfonsina Storni" },
{ text: "Dios mío, estoy llena de dudas, de preguntas sin respuestas.", author: "Alfonsina Storni" },
{ text: "Voy a dormir, nodriza mía, acuéstame.", author: "Alfonsina Storni" },
{ text: "Escribir es recordar, pero leer también es recordar.", author: "Fernando Vallejo" },
{ text: "La literatura es fuego, es subversión de la realidad.", author: "Mario Vargas Llosa" },
{ text: "La patria es el olvido.", author: "Roberto Bolaño" },
{text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    {text: "El conocimiento se adquiere por la experiencia, todo lo demás es solo información.",author: "Albert Einstein" },
    { text: "El mundo es un libro y aquellos que no viajan solo leen una página.", author: "San Agustín" },
    { text: "La vida es una aventura atrevida o nada en absoluto.", author: "Helen Keller" },
    { text: "El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer.", author: "Walter Bagehot" },
    { text: "La perseverancia es la clave del éxito.", author: "Confucio" },
    { text: "La felicidad es una dirección, no un destino.", author: "Zig Ziglar" },
    {text: "La vida es corta, rompe las reglas, perdona rápido, besa despacio, ama de verdad, ríe sin control y nunca te arrepientas de nada que te haya hecho sonreír.", author: "Mark Twain", },
    { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
    {text: "El único límite a nuestra realización del mañana serán nuestras dudas de hoy.", author: "Franklin D. Roosevelt",},
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    {text: "La vida es un regalo, y nos ofrece el privilegio, la oportunidad y la responsabilidad de devolver algo al convertirnos en más.", author: "Tony Robbins", },
    { text: "La sabiduría comienza en el asombro.", author: "Sócrates" },
    { text: "La felicidad es un hábito, cultívalo.", author: "Elbert Hubbard" },
    { text: "La vida es un largo aprendizaje de la pérdida.", author: "Jean Cocteau" },
    { text: "El propósito de la vida es vivir, y vivir plenamente.", author: "Jack London" },
    { text: "La belleza está en los ojos del que mira.", author: "Margaret Wolfe Hungerford" },
    { text: "El silencio es oro.", author: "Proverbio" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "El tiempo es un gran maestro, se dice, el problema es que mata a sus alumnos.", author: "Hector Berlioz" },
    {text: "La vida es un desafío que afrontar, una felicidad que merecer, una aventura que intentar.",author: "Madre Teresa",},
    {text: "El mayor viajero no es el que ha dado diez veces la vuelta al mundo, sino el que ha dado una sola vez la vuelta a sí mismo.",author: "Gandhi",},
    { text: "La vida es un arte, hay que pintarla con los colores del alma.", author: "Vincent Van Gogh" },
    { text: "La felicidad es una flor que no hay que coger.", author: "André Gide" },
    { text: "La vida es un sueño, despierta.", author: "Proverbio chino" },
    { text: "El conocimiento es un arma.", author: "Francis Bacon" },
    { text: "La verdad es una, pero los caminos para llegar a ella son múltiples.", author: "Gandhi" },
    { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
    { text: "La vida es un misterio que hay que vivir, no un problema que resolver.", author: "Gandhi" },
    {text: "La felicidad es a menudo lo único que puedes dar sin tenerla, y es dándola como la adquieres.", author: "Voltaire",},
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    {text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer", },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    {text: "El conocimiento se adquiere por la experiencia, todo lo demás es solo información.", author: "Albert Einstein", },
    { text: "El mundo es un libro y aquellos que no viajan solo leen una página.", author: "San Agustín" },
    { text: "La vida es una aventura atrevida o nada en absoluto.", author: "Helen Keller" },
    { text: "El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer.", author: "Walter Bagehot" },
    { text: "La perseverancia es la clave del éxito.", author: "Confucio" },
    { text: "La felicidad es una dirección, no un destino.", author: "Zig Ziglar" },
    {text: "La vida es corta, rompe las reglas, perdona rápido, besa despacio, ama de verdad, ríe sin control y nunca te arrepientas de nada que te haya hecho sonreír.",author: "Mark Twain", },
    { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
    {text: "El único límite a nuestra realización del mañana serán nuestras dudas de hoy.",author: "Franklin D. Roosevelt", },
    {text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    {text: "La vida es un regalo, y nos ofrece el privilegio, la oportunidad y la responsabilidad de devolver algo al convertirnos en más.", author: "Tony Robbins",},
    { text: "La sabiduría comienza en el asombro.", author: "Sócrates" },
    { text: "La felicidad es un hábito, cultívalo.", author: "Elbert Hubbard" },
    { text: "La vida es un largo aprendizaje de la pérdida.", author: "Jean Cocteau" },
    { text: "El propósito de la vida es vivir, y vivir plenamente.", author: "Jack London" },
    { text: "La belleza está en los ojos del que mira.", author: "Margaret Wolfe Hungerford" },
    { text: "El silencio es oro.", author: "Proverbio" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "El tiempo es un gran maestro, se dice, el problema es que mata a sus alumnos.", author: "Hector Berlioz" },
    {text: "La vida es un desafío que afrontar, una felicidad que merecer, una aventura que intentar.",author: "Madre Teresa",},
    { text: "La vida es un arte, hay que pintarla con los colores del alma.", author: "Vincent Van Gogh" },
    { text: "La felicidad es una flor que no hay que coger.", author: "André Gide" },
    { text: "La vida es un sueño, despierta.", author: "Proverbio chino" },
    { text: "El conocimiento es un arma.", author: "Francis Bacon" },
    { text: "La verdad es una, pero los caminos para llegar a ella son múltiples.", author: "Gandhi" },
  ],
  ar: [
{ text: "اعرف نفسك تعرف ربك", author: "مثل عربي" },
{ text: "خير الناس أنفعهم للناس", author: "حديث شريف" }, 
{ text: "إنما الأعمال بالنيات", author: "حديث شريف" },
{ text: "من صبر ظفر", author: "مثل عربي" },
{ text: "الحكمة ضالة المؤمن", author: "حديث شريف" },
{ text: "من تواضع لله رفعه", author: "حديث شريف" },
{ text: "الدنيا دار ممر والآخرة دار مقر", author: "حكمة إسلامية" },
{ text: "ليس الغنى عن كثرة العرض ولكن الغنى غنى النفس", author: "حديث شريف" },
{ text: "المؤمن مرآة أخيه", author: "حديث شريف" },
{ text: "من لم يشكر الناس لم يشكر الله", author: "حديث شريف" },
{ text: "اعمل لدنياك كأنك تعيش أبداً واعمل لآخرتك كأنك تموت غداً", author: "علي بن أبي طالب" },
{ text: "الحياة مدرسة والتجارب معلمها", author: "حكمة عربية" },
{ text: "من أراد أن يطاع في المستحيل فليترك الممكن", author: "حكمة عربية" },
{ text: "العبرة بالخواتيم", author: "مثل عربي" },
{ text: "الحق أبلج والباطل لجلج", author: "مثل عربي" },
{ text: "من أعان ظالماً سلطه الله عليه", author: "حديث شريف" },
{ text: "الناس معادن كمعادن الذهب والفضة", author: "حديث شريف" },
{ text: "إذا أردت أن تطاع فأمر بما يستطاع", author: "حكمة عربية" },
{ text: "لا تكن ليناً فتعصر، ولا قاسياً فتكسر.", author: "مثل عربي" },
{ text: "كل إناء بما فيه ينضح.", author: "مثل عربي" },
{ text: "لا تحقرن من المعروف شيئاً.", author: "حديث شريف" },
{ text: "ما خاب من استخار ولا ندم من استشار.", author: "مثل عربي" },
{ text: "المرء على دين خليله فلينظر أحدكم من يخالل.", author: "حديث شريف" },
{ text: "إن مع العسر يسرا.", author: "القرآن الكريم" },
{ text: "لا تحزن إن الله معنا.", author: "القرآن الكريم" },
{ text: "لا تكن كمن يجمع الحطب ليحرق نفسه.", author: "مثل عربي" },
{ text: "إذا لم تكن ذئباً أكلتك الذئاب.", author: "مثل عربي" },
{ text: "من شب على شيء شاب عليه.", author: "مثل عربي" },
{ text: "لا تلوموا الناس ولكن لوموا أنفسكم.", author: "مثل عربي" },
{ text: "المرء حيث يضع نفسه.", author: "مثل عربي" },
{ text: "إنما الأمم الأخلاق ما بقيت فإن هم ذهبت أخلاقهم ذهبوا.", author: "أحمد شوقي" },
{ text: "إذا الشعب يوماً أراد الحياة فلا بد أن يستجيب القدر.", author: "أبو القاسم الشابي" },
{ text: "أنا لا أكتب إلا لأني أحب أن أكتب، ولأني لا أستطيع أن أعيش بدون أن أكتب.", author: "محمود درويش" },
{ text: "على هذه الأرض ما يستحق الحياة.", author: "محمود درويش" },
{ text: "فكر بغيرك.", author: "محمود درويش" },
{ text: "الوجود يسبق الجوهر.", author: "جان بول سارتر" },
{ text: "كل شيء مسموح به إذا كنت مستعدًا لدفع الثمن.", author: "ألبير كامو" },
{ text: "الحياة تبدأ عندما ينتهي اليأس.", author: "جان بول سارتر" },
{ text: "كلنا ننظر إلى النجوم، لكننا لا نرى الشيء نفسه.", author: "جورج كارلين" },
{ text: "الحقيقة مثل الشعر، معظم الناس يكرهونه.", author: "تشارلز بوكوفسكي" },
{ text: "كن نفسك، الجميع الآخرون محتلون بالفعل.", author: "أوسكار وايلد" },
{ text: "أنا من هناك، أنا من هنا، ولست هناك، ولست هنا.", author: "محمود درويش" },
{ text: "لا تسألني عن الحب، بل اسألني عن قلبي.", author: "محمود درويش" },
{ text: "الآن، بعد أن أصبحتُ رجلاً، أرى أن الطفولة كانت أجمل.", author: "محمود درويش" },
{ text: "الروح لا تطلب شيئاً إلا الحب، والحب لا يطلب شيئاً إلا أن يكون هو كل شيء.", author: "جلال الدين الرومي" },
{ text: "ما تبحث عنه يبحث عنك.", author: "جلال الدين الرومي" },
{ text: "لا تكن بلا حب، لئلا تشعر بأنك ميت.", author: "جلال الدين الرومي" },
{ text: "أنت لست قطرة في محيط، أنت المحيط كله في قطرة.", author: "جلال الدين الرومي" },
{ text: "دع جمال ما تحب يكون ما تفعله.", author: "جلال الدين الرومي" },
{ text: "هناك صوت لا يستخدم الكلمات. استمع إليه.", author: "جلال الدين الرومي" },
{ text: "الحب هو الجسر بينك وبين كل شيء.", author: "جلال الدين الرومي" },
{ text: "لا تحزن. أي شيء تفقده سيعود إليك بشكل آخر.", author: "جلال الدين الرومي" },
{ text: "الكون كله موجود في داخلك. اسأل نفسك كل شيء.", author: "جلال الدين الرومي" },
{ text: "القلب هو عين الروح.", author: "جلال الدين الرومي" },
{ text: "إذا غامَرْتَ في شَرَفٍ مَرُومِ فلا تَقنَعْ بما دونَ النُّجُومِ.", author: "المتنبي" },  
{ text: "الظَّلْمُ مِن شِيَمِ النُّفُوسِ، فإن تَجِدْ ذَا عِفَّةٍ فَلِعِلَّةٍ لا يَظْلِمُ.", author: "ابن خلدون" },  
{ text: "النَّاسُ أَعْدَاءُ مَا جَهِلُوا.", author: "علي بن أبي طالب" },  
{ text: "لَيْسَ الْفَقْرُ أَنْ لا تَمْلِكَ دِرْهَمًا، الْفَقْرُ أَنْ لا تَكُونَ لَكَ قِيمَةٌ.", author: "عمر بن الخطاب" },  
{ text: "الحياةُ لا تُفْهَمُ إِلَّا إِلَى الْوَرَاءِ، وَلَكِنْ يَجِبُ أَنْ تُعَاشَ إِلَى الأَمَامِ.", author: "جبران خليل جبران" },  
{ text: "لَوْ كَانَ الْجَهْلُ رَجُلًا لَقَتَلْتُهُ.", author: "علي بن أبي طالب" },  
{ text: "الْكِتَابُ خَيْرُ جَلِيسٍ فِي الزَّمَانِ.", author: "المتنبي" },    
{ text: "مَنْ لا يَعْرِفُ الصَّبْرَ لا يَعْرِفُ النَّجَاحَ.", author: "نجيب محفوظ" },  
{ text: "الْحُرِّيَّةُ هِيَ الْحَيَاةُ، وَلَكِنْ لا حُرِّيَّةَ بِلا فَضِيلَةٍ.", author: "أحمد شوقي" },    
{ text: "الْقُلُوبُ أَوْعِيَةٌ وَالشِّفَاهُ أَقْفَالُهَا وَالأَلْسُنُ مَفَاتِيحُهَا، فَلْيَحْفَظْ كُلٌّ مِنَّا مِفْتَاحَ سِرِّهِ.", author: "ابن سينا" },  
{ text: "الرَّاحَةُ تُولِدُ الرُّكُودَ، وَالتَّعَبُ يُولِدُ الْعَظَمَةَ.", author: "طه حسين" },  
{ text: "الْخَوْفُ مِنَ الْمَوْتِ خَوْفٌ مِنَ الْحَيَاةِ نَفْسِهَا.", author: "ميخائيل نعيمة" },  
{ text: "الْحِكْمَةُ ضَالَّةُ الْمُؤْمِنِ، فَحَيْثُ وَجَدَهَا فَهُوَ أَحَقُّ بِهَا.", author: "علي بن أبي طالب" },  
{ text: "إِذَا كَانَ الْكَلامُ مِنْ فِضَّةٍ، فَالسُّكُوتُ مِنْ ذَهَبٍ.", author: "علي بن أبي طالب" },  
{ text: "الْإِنْسَانُ عَدُوُّ مَا جَهِلَ.", author: "ابن خلدون" },  
{ text: "الْحُبُّ هُوَ النُّورُ الَّذِي يُضِيءُ الْكَوْنَ.", author: "جبران خليل جبران" },  
{ text: "الْعَيْنُ لا تَرَى الذَّاتَ إِلَّا بِالْمِرْآةِ، وَالرُّوحُ لا تَرَى نَفْسَهَا إِلَّا فِي الْحُبِّ.", author: "جبران خليل جبران" },  
{ text: "لَيْسَ الْجَمَالُ بِأَثْوَابٍ تُزَيِّنُنَا، إِنَّ الْجَمَالَ جَمَالُ الْعِلْمِ وَالْأَدَبِ.", author: "أحمد شوقي" },  
{ text: "الْحَقُّ يُقَالُ وَلَوْ كَانَ مُرًّا.", author: "عمر بن الخطاب" },
{ text: "الحب لا يعطي إلا نفسه، ولا يأخذ إلا من نفسه.", author: "جبران خليل جبران" },  
{ text: "الصمت أبلغ من الكلام، لأن الصمت لا يكذب.", author: "جبران خليل جبران" },  
{ text: "أنت أعمق مما نزلت إليه نفسي، وأعلى مما نهضت إليه روحي.", author: "جبران خليل جبران" },  
{ text: "في قلب كل شتاء ربيع نابض، ووراء كل ليل فجر باسم.", author: "جبران خليل جبران" },  
{ text: "الحياة ليست إلا ظلًا زائلًا، إلا إذا أحببت.", author: "جبران خليل جبران" },  
{ text: "أنت نصفي الذي كنتُ أبحث عنه، والنصف الذي لم أكن أعرف أني افتقدته.", author: "جبران خليل جبران" },  
{ text: "القلوب المتوضعة بالحب لا تموت أبدًا.", author: "جبران خليل جبران" },  
{ text: "لا تستطيع أن تضحك وتكون قاسيًا في نفس اللحظة.", author: "جبران خليل جبران" },  
{ text: "الوحدة حكمة، والجماعة قوة، والحب سلام.", author: "جبران خليل جبران" },  
{ text: "الموت ليس إلا أن نخلع ثوبًا قديمًا لنلبس آخر جديدًا.", author: "جبران خليل جبران" },  
{ text: "الحياة ليست سوى ومضة، فاجعلها ومضة نور.", author: "ميخائيل نعيمة" },  
{ text: "الروح لا تموت، بل تخلع ثوبًا باليًا لترتدي ثوبًا جديدًا.", author: "ميخائيل نعيمة" },  
{ text: "كل شيء في الكون يغني، فلماذا لا تغني أنت؟", author: "ميخائيل نعيمة" },  
{ text: "السعادة ليست في الوصول، بل في السير نحو القمة.", author: "ميخائيل نعيمة" },  
{ text: "لا شيء يولد عظيماً، العظمة تُكتسب بالعزم.", author: "ميخائيل نعيمة" },    
{ text: "الوحدة ليست فراغًا، بل هي ملكوت الروح.", author: "مي زيادة" },  
{ text: "قلبي يحدثني بأني ميت، وأني غير ميت!", author: "إيليا أبو ماضي" },  
{ text: "ما أبعد الغاية إلا على من لا يريد السير!", author: "إيليا أبو ماضي" },  
{ text: "أنا لا أشتاق إلى وطنٍ، بل أشتاق إلى زمنٍ كان فيه وطني.", author: "إيليا أبو ماضي" },  
{ text: "الحب ليس حبًا إذا كان مشروطًا.", author: "إيليا أبو ماضي" },  
{ text: "كل شيء يموت، إلا الأمل.", author: "إيليا أبو ماضي" },  
{ text: "الحقيقة مثل الشمس، لا يمكنك حجبها بيديك.", author: "أمين الريحاني" },  
{ text: "الحرية لا تُعطى، بل تُؤخذ.", author: "أمين الريحاني" },  
{ text: "الوطن ليس أرضًا، بل ضمير.", author: "أمين الريحاني" },   
{ text: "لا تبحث عن السعادة، بل اصنعها.", author: "أمين الريحاني" },    
{ text: "الليل ليس سوى ظل النهار، والحزن ليس سوى ظل الفرح.", author: "مجهول (على نهج جبران)" },  
{ text: "الروح لا تعرف حدودًا، فكيف تحبسها في جسد؟", author: "مجهول (على نهج جبران)" },  
{ text: "الزمن لا يمر، نحن من نمر فيه.", author: "مجهول (على نهج جبران)" }, 
{ text: "وَمَن يَتَّقِ ٱللَّهَ يَجْعَل لَّهُۥ مَخْرَجًۭا", author: "القرآن الكريم (الطلاق: ٢)" },
{ text: "إِنَّ مَعَ ٱلْعُسْرِ يُسْرًۭا", author: "القرآن الكريم (الشرح: ٥)" },
{ text: "وَتَوَكَّلْ عَلَى ٱلْحَىِّ ٱلَّذِى لَا يَمُوتُ", author: "القرآن الكريم (الفرقان: ٥٨)" },
{ text: "وَلَنَبْلُوَنَّكُم بِشَىْءٍۢ مِّنَ ٱلْخَوْفِ وَٱلْجُوعِ وَنَقْصٍۢ مِّنَ ٱلْأَمْوَٰلِ وَٱلْأَنفُسِ وَٱلثَّمَرَٰتِۗ وَبَشِّرِ ٱلصَّٰبِرِينَ", author: "القرآن الكريم (البقرة: ١٥٥)" }, 
{ text: "إذا المرء لم يدنس من اللؤم عرضه فكل رداء يرتديه جميل", author: "المتنبي" },
{ text: "أعز مكان في الدنا سرج سابح وخير جليس في الزمان كتاب", author: "أبو الطيب المتنبي" },
{ text: "ذو العقل يشقى في النعيم بعقله وأخو الجهالة في الشقاوة ينعم", author: "الحطيئة" },
{ text: "الكتابة فعل مقاومة ضد النسيان", author: "أدونيس" },
{ text: "الوطن ليس أرضاً نعيش عليها بل هو ذاكرة تحيا فينا", author: "إدوارد سعيد" },
{ text: "الثقافة هي الذاكرة التي تحفظ للأمة هويتها", author: "طه حسين" },
{ text: "العارف من عرف نفسه فانكسر لها", author: "الحسن البصري" },
{ text: "من عرف نفسه اشتغل بإصلاحها عن عيوب الناس", author: "ابن عطاء الله السكندري" },
{ text: "القلب مزرعة فازرع فيه الحكمة ولا تزرع فيه غيرها", author: "أبو حامد الغزالي" },
{ text: "من علامة الإيمان أن تحب للناس ما تحب لنفسك", author: "حديث نبوي" },
{ text: "المنفى ليس مكاناً.. المنفى هو ذاكرة لا تجد لها عنواناً", author: "أمجد ناصر" },
{ text: "الوطن هو ذلك المكان الذي حين تغادره لأول مرة تكتشف أنك لم تغادره", author: "بهاء طاهر" },
{ text: "المنفى ليس غياباً عن المكان بل حضور في الزمان", author: "محمود درويش" },
{ text: "كلّنا نحبّ، لكن بقلوبٍ متفرقة", author: "نازك الملائكة" },
{ text: "أنا لغتي، أنا هويتي الضائعة", author: "فدوى طوقان" },
{ text: "في حضرة الغياب، نتعلم كيف نكون حاضرين", author: "سعدي يوسف" },
{ text: "الحرية هي أن تقول 'لا' عندما يتوقع منك الجميع 'نعم'", author: "علي الوردي" },
{ text: "الحضارة هي أن نتحاور، لا أن نتصارع", author: "مالك بن نبي" },
{ text: "الوعي هو أول خطوة نحو التحرر", author: "فرانتز فانون" },
{ text: "الثورة ليست حدثاً، بل هي مسار طويل من المقاومة", author: "سمير أمين" },
{ text: "الكتابة هي مقاومة النسيان السياسي", author: "عبد الرحمن منيف" },
{ text: "الهوية ليست سجناً نعيش فيه، بل نافذة نطل منها على العالم", author: "هشام جعيط" },
{ text: "الوجود يسبق الماهية", author: "ابن عربي" },
{ text: "الحب هو الطريق الوحيد لمعرفة الذات", author: "محيي الدين بن عربي" },
{ text: "الحرية تبدأ حيث ينتهي الخوف", author: "عبد الكريم الخطابي" },
{ text: "الهوية ليست جداراً بل جسر", author: "الطاهر وطار" },
{ text: "الثقافة هي مقاومة الاندثار", author: "مولود فرعون" },
{ text: "لا نستورد الحرية كالبضائع، نصنعها بأيدينا", author: "مالك حداد" },
{ text: "الحضارة تنشأ عندما يتحول الإنسان من حالة القابلية للاستعمار إلى الفاعلية الحضارية", author: "مالك بن نبي" },
{ text: "المشكلة ليست في الحديد والنار، بل في الإنسان والتراب", author: "مالك بن نبي" },
{ text: "الاستعمار الفكري أخطر من الاستعمار العسكري", author: "مالك بن نبي" },
{ text: "كل أمة تنشر في الكون رسالة خاصة بها", author: "مالك بن نبي" },
{ text: "الزمن ليس محايداً، إما صديقاً للحضارة أو عدواً لها", author: "مالك بن نبي" },
{ text: "المريد الصادق يرى الله في كل شيء", author: "أبو الحسن الشاذلي" },
{ text: "القلب مرآة إن صقلها الذكر رأى بها الحق", author: "أحمد التيجاني" },
{ text: "السالك إلى الله لا يخشى الفقر ولا يخاف العار", author: "عبد القادر الجيلاني" },
{ text: "المحبة سفينة النجاة", author: "ابن عطاء الله السكندري" },
{ text: "الذكر هو دواء القلوب المريضة", author: "الغزالي" },
{ text: "الكون كتاب مفتوح لمن يعرف قراءة آياته", author: "ابن باجة" },
{ text: "النور الإلهي والعلم التجريبي وجهان لحقيقة واحدة", author: "ابن طفيل" },
{ text: "كل ذرة في الكون تسبح بحمد خالقها", author: "محيي الدين بن عربي" },
{ text: "الموت لا يسرق منا الحياة، لكنه يسرق منها الوهم", author: "أمين معلوف" },
{ text: "الجحيم ليس مكاناً نذهب إليه، بل هو الوضع الذي نعيش فيه", author: "مصطفى محمود" },
{ text: "أحياناً نعيش لنشهد موتنا البطيء", author: "نجيب محفوظ" },
{ text: "الجنون هو القاعدة، والعقل هو الاستثناء", author: "مصطفى صادق الرافعي" },
{ text: "أتعلمون ما هو الجحيم؟ أن تحب ولا تُحب في المقابل", author: "جان بول سارتر" },
{ text: "كلنا نموت مرتين: مرة عندما تتوقف قلوبنا، ومرة عندما ينطق اسمنا للمرة الأخيرة", author: "مثل صيني" },
{ text: "الظلام ليس عدواً للنور، بل هو أمه", author: "مثل تركي" },
{ text: "كلما ازددت علماً، ازددت حزناً", author: "ابن المقفع" },
{ text: "الشر ليس سوى الجانب الآخر للخير", author: "فريدريك نيتشه" },
{ text: "إننا لا نحيا إلا لنعاني", author: "فيودور دوستويفسكي" },
{ text: "كل شيء يولد من الفوضى، ويعود إليها", author: "هرقليطس" },
{ text: "أتعس الناس من لا يعرف سبب تعاسته", author: "سيغموند فرويد" },
{ text: "الموت ليس أسوأ ما في الحياة، لكن الخوف منه هو الأسوأ", author: "ألبير كامو" },
{ text: "الشر المطلق لا وجود له، كما أن الخير المطلق لا وجود له", author: "ألبير كامو" },
{ text: "الذكريات هي الجحيم الذي نحمله في عقولنا", author: "خورخي لويس بورخيس" },
{ text: "الحياة ليست سوى ظل عابر", author: "وليم شكسبير" },
{ text: "أتعس أنواع الوحدة هي أن تكون وحيداً بين الناس", author: "تشارلز ديكنز" },
{ text: "الشر لا ينتصر لأن الخير أقوى، بل لأنه أكثر تنظيماً", author: "مثل ألماني" },
{ text: "الحياة معركة نخسرها جميعاً في النهاية", author: "هنري دي مونترلان" },
{ text: "أقسى أنواع الألم هو ألم الذاكرة", author: "فيكتور هوجو" },
{ text: "كلنا نموت وحيدين، حتى لو كنا محاطين بالآخرين", author: "ماريو بارغاس يوسا" },
{ text: "الشر ليس سوى الجانب المظلم من الطبيعة البشرية", author: "كارل يونغ" },
{ text: "الحياة سلسلة من الخيبات تنتهي بخيبة أمل كبرى", author: "صموئيل بيكيت" },
{ text: "كلنا نحمل في داخلنا شيطاناً صغيراً", author: "توماس مان" },
{ text: "الشر ليس سوى غياب الضوء", author: "دانتي أليغييري" },
{ text: "الخوف هو المرض الوحيد الذي لا دواء له", author: "باولو كويلو" },
{ text: "الحياة معركة نخوضها كل يوم، ونخسرها في النهاية", author: "ألبير كامو" },
{ text: "كل إنسان يحمل في داخله مقبرة", author: "إميل سيوران" },
{ text: "الشر ليس سوى الجانب الآخر للحب", author: "ماركيز دي ساد" },
{ text: "الحياة سجن كبير، والموت هو الحرية الوحيدة", author: "أنطوان دي سانت إكزوبيري" },
{ text: "كلنا نحمل في داخلنا وحشاً", author: "ويليام غولدينغ" },
{ text: "الشر ليس سوى الجانب المظلم من الروح", author: "كارلوس كاستانيدا" },
{ text: "الخوف هو السجن الذي نبنيه لأنفسنا", author: "ماريو فارغاس يوسا" },
{ text: "الحياة مثل الكتاب، من لا يسافر فيها يقرأ صفحة واحدة فقط", author: "سانت أوغسطين" },
{ text: "التجارب هي أفضل معلم، لكن الدروس تكون باهظة الثمن", author: "مثل ألماني" },
{ text: "لا تؤجل عمل اليوم إلى الغد، فالوقت كالسيف إن لم تقطعه قطعك", author: "ابن خلدون" },
{ text: "إذا أردت أن تعرف قيمة الحرية، فاسأل من عاش تحت الاستعمار", author: "مالك بن نبي" },
{ text: "الصديق الحقيقي هو الذي يكون حاضراً عندما يكون الجميع غائبين", author: "مثل عربي" },
{ text: "لا قيمة للمال إذا فقدت الأصدقاء", author: "مثل مصري" },
{ text: "كن طيباً حتى لو لم يقدّر أحد طيبتك، فالطيبة ثوب لا يبلى", author: "مثل سوري" },
{ text: "الخير الذي تفعله اليوم قد ينساه الناس غداً، لكن الله لا ينسى", author: "حديث شريف" },
{ text: "أجمل ما في الإنسان قلبه الطيب قبل مظهره الجميل", author: "مثل خليجي" },
{ text: "الأمل هو الشيء الوحيد الذي لا يمكنك العيش بدونه", author: "نجيب محفوظ" },
{ text: "كل شتاء يتبعه ربيع، وكل ليل يتبعه فجر", author: "مثل فلسطيني" },
{ text: "العلم هو نور العقل، والجهل هو ظلام الروح", author: "ابن سينا" },
{ text: "اقرأ لتكون حراً، فالقلم أقوى من السيف", author: "طه حسين" },
{ text: "المعرفة كنز لا يفنى، والجهل فقر لا ينتهي", author: "مثل عربي" },
{ text: "الليلُ ليس غيابَ النور، بل هو حوارٌ بين النجومِ والوحشة", author: "ياسين كاتب" },  
{ text: "الصمتُ ليس فراغًا، بل هو فضاءٌ مملوءٌ بالأسئلة", author: "الطاهر وطار" },  
{ text: "البحرُ يعلمنا أنّ الحياةَ ليست عمقاً ولا عرضاً، بل حركةٌ لا تتوقف", "author": "محمد ديب" },  
{ text: "الطفولةُ وطنٌ نحملهُ في جيبنا كحجرٍ ناعمٍ من النهر", "author": "مولود معمري" } ,
{ text: "الكتابةُ هي الوطنُ الأخيرُ لمن لا وطنَ له", author: "الطاهر وطار" },  
{ text: "كيفَ نكتبُ عن الحرية ونحنُ لم نرَ إلا القيودَ؟", author: "رشيد ميموني" },  

  ],
}

// Track recent quotes to avoid repetition
const recentQuotes: { [key: string]: Quote[] } = {}
const MAX_RECENT_QUOTES = 0 // Increased to track more recent quotes

export async function getRandomQuote(language: string): Promise<Quote> {
  const languageQuotes = quotes[language] || quotes.en

  // Initialize recent quotes for language if not exists
  if (!recentQuotes[language]) {
    recentQuotes[language] = []
  }

  // Filter out recently shown quotes
  const availableQuotes = languageQuotes.filter(
    (quote) => !recentQuotes[language].some((recent) => recent.text === quote.text && recent.author === quote.author),
  )

  // If all quotes have been shown recently, reset the recent list
  const quotesToChooseFrom = availableQuotes.length > 0 ? availableQuotes : languageQuotes

  // Select random quote
  const randomIndex = Math.floor(Math.random() * quotesToChooseFrom.length)
  const selectedQuote = quotesToChooseFrom[randomIndex]

  // Add to recent quotes
  recentQuotes[language].push(selectedQuote)

  // Keep only the last MAX_RECENT_QUOTES
  if (recentQuotes[language].length > MAX_RECENT_QUOTES) {
    recentQuotes[language] = recentQuotes[language].slice(-MAX_RECENT_QUOTES)
  }

  // Reset recent quotes if we used all available quotes (and there are more than MAX_RECENT_QUOTES total)
  // This ensures we don't get stuck if the total quotes are less than MAX_RECENT_QUOTES
  if (availableQuotes.length === 0 && languageQuotes.length > MAX_RECENT_QUOTES) {
    recentQuotes[language] = [selectedQuote]
  } else if (availableQuotes.length === 0 && languageQuotes.length <= MAX_RECENT_QUOTES) {
    // If total quotes are less than or equal to MAX_RECENT_QUOTES, just reset to the current one
    recentQuotes[language] = [selectedQuote]
  }

  return selectedQuote
}
 //arabic quotes : 146 
 //spanish quotes :170
 //italian quotes : 167
 //french quotes : 154
 //english quotes :154
