interface Quote {
  text: string
  author: string
}

interface QuoteDatabase {
  [key: string]: Quote[]
}

// Quote database with inspirational and philosophical quotes
const quotes: QuoteDatabase = {
  en: [
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
    { text: "Yesterday is history, tomorrow is a mystery, today is a gift.", author: "Eleanor Roosevelt" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "You learn more from failure than from success.", author: "Unknown" },
    {
      text: "If you are working on something exciting that you really care about, you don't have to be pushed.",
      author: "Steve Jobs",
    },
    {
      text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
      author: "Winston Churchill",
    },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    {
      text: "In this life we cannot do great things. We can only do small things with great love.",
      author: "Mother Teresa",
    },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    {
      text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
      author: "Winston Churchill",
    },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    {
      text: "The only person you are destined to become is the person you decide to be.",
      author: "Ralph Waldo Emerson",
    },
    {
      text: "Go confidently in the direction of your dreams. Live the life you have imagined.",
      author: "Henry David Thoreau",
    },
    {
      text: "When I was 5 years old, my mother always told me that happiness was the key to life.",
      author: "John Lennon",
    },
    { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    {
      text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
      author: "Ralph Waldo Emerson",
    },
    {
      text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
      author: "Nelson Mandela",
    },
    { text: "The future belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    {
      text: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
      author: "Zig Ziglar",
    },
    {
      text: "The only limit to our realization of tomorrow will be our doubts of today.",
      author: "Franklin D. Roosevelt",
    },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "The greatest wealth is to live content with little.", author: "Plato" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    {
      text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
      author: "Ralph Waldo Emerson",
    },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "The greatest wealth is to live content with little.", author: "Plato" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    {
      text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
      author: "Ralph Waldo Emerson",
    },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "The greatest wealth is to live content with little.", author: "Plato" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    {
      text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
      author: "Ralph Waldo Emerson",
    },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "The greatest wealth is to live content with little.", author: "Plato" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    {
      text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
      author: "Ralph Waldo Emerson",
    },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "The greatest wealth is to live content with little.", author: "Plato" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    {
      text: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
      author: "Ralph Waldo Emerson",
    },
  ],
  fr: [
    { text: "Il n'y a point de génie sans un grain de folie.", author: "Aristote" },
    { text: "La vie est un sommeil, l'amour en est le rêve.", author: "Alfred de Musset" },
    {
      text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
      author: "Antoine de Saint-Exupéry",
    },
    { text: "L'enfer, c'est les autres.", author: "Jean-Paul Sartre" },
    { text: "Je pense, donc je suis.", author: "René Descartes" },
    { text: "La liberté, c'est la liberté de dire que deux et deux font quatre.", author: "George Orwell" },
    { text: "Il faut cultiver notre jardin.", author: "Voltaire" },
    { text: "L'art de vivre consiste en un subtil mélange entre lâcher prise et tenir bon.", author: "Henri Lewis" },
    { text: "Le bonheur n'est pas une destination, c'est une façon de voyager.", author: "Margaret Lee Runbeck" },
    {
      text: "Celui qui déplace la montagne, c'est celui qui commence à enlever les petites pierres.",
      author: "Confucius",
    },
    { text: "La vraie générosité envers l'avenir consiste à tout donner au présent.", author: "Albert Camus" },
    { text: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.", author: "George Sand" },
    { text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" },
    {
      text: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
      author: "Albert Einstein",
    },
    {
      text: "Le courage n'est pas l'absence de peur, mais la capacité de vaincre ce qui fait peur.",
      author: "Nelson Mandela",
    },
    { text: "Il vaut mieux faire que dire, il vaut mieux agir que se plaindre.", author: "Winston Churchill" },
    { text: "La seule façon de faire du bon travail, c'est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
    { text: "Ce n'est pas la montagne que nous conquérons, mais nous-mêmes.", author: "Sir Edmund Hillary" },
    {
      text: "La différence entre l'ordinaire et l'extraordinaire, c'est ce petit quelque chose en plus.",
      author: "Jimmy Johnson",
    },
    { text: "Le succès c'est d'aller d'échec en échec sans perdre son enthousiasme.", author: "Winston Churchill" },
    {
      text: "La plus grande révolution de notre génération est la découverte que l'être humain peut changer sa vie.",
      author: "William James",
    },
    { text: "Il n'est jamais trop tard pour être ce que vous auriez pu être.", author: "George Eliot" },
    { text: "La vie est trop importante pour être prise au sérieux.", author: "Oscar Wilde" },
    { text: "Soyez le changement que vous voulez voir dans le monde.", author: "Gandhi" },
    {
      text: "L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.",
      author: "Nelson Mandela",
    },
    {
      text: "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.",
      author: "Oscar Wilde",
    },
    { text: "Le temps est la chose la plus précieuse que nous puissions dépenser.", author: "Théophraste" },
    {
      text: "La sagesse, c'est d'avoir des rêves suffisamment grands pour ne pas les perdre de vue.",
      author: "Oscar Wilde",
    },
    { text: "Chaque expert était autrefois un débutant.", author: "Helen Hayes" },
    { text: "Le doute est le commencement de la sagesse.", author: "Aristote" },
    { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
    {
      text: "Le bonheur est souvent la seule chose que l'on puisse donner sans l'avoir et c'est en le donnant qu'on l'acquiert.",
      author: "Voltaire",
    },
    { text: "La seule façon de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès.", author: "Albert Schweitzer" },
    { text: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
    {
      text: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.",
      author: "Albert Einstein",
    },
    { text: "Le monde est un livre et ceux qui ne voyagent pas n'en lisent qu'une page.", author: "Saint Augustin" },
    { text: "La vie est une aventure audacieuse ou rien du tout.", author: "Helen Keller" },
    {
      text: "Le plus grand plaisir dans la vie est de faire ce que les gens disent que vous ne pouvez pas faire.",
      author: "Walter Bagehot",
    },
    { text: "La persévérance est la clé du succès.", author: "Confucius" },
    { text: "Le bonheur est une direction, pas une destination.", author: "Zig Ziglar" },
    {
      text: "La vie est courte, brisez les règles, pardonnez vite, embrassez lentement, aimez vraiment, riez sans contrôle et ne regrettez jamais rien qui vous ait fait sourire.",
      author: "Mark Twain",
    },
    { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
    {
      text: "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui.",
      author: "Franklin D. Roosevelt",
    },
    { text: "Le meilleur moyen de prédire l'avenir est de le créer.", author: "Peter Drucker" },
    {
      text: "La vie est un cadeau, et elle nous offre le privilège, l'opportunité et la responsabilité de donner quelque chose en retour en devenant plus.",
      author: "Tony Robbins",
    },
    { text: "La sagesse commence dans l'émerveillement.", author: "Socrate" },
    { text: "Le bonheur est une habitude, cultivez-le.", author: "Elbert Hubbard" },
    { text: "La vie est un long apprentissage de la perte.", author: "Jean Cocteau" },
    { text: "Le but de la vie est de vivre, et de vivre pleinement.", author: "Jack London" },
    { text: "La beauté est dans les yeux de celui qui regarde.", author: "Margaret Wolfe Hungerford" },
    { text: "Le silence est d'or.", author: "Proverbe" },
    { text: "La patience est amère, mais son fruit est doux.", author: "Jean-Jacques Rousseau" },
    { text: "Le temps est un grand maître, dit-on, le malheur est qu'il tue ses élèves.", author: "Hector Berlioz" },
    { text: "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", author: "Mère Teresa" },
    {
      text: "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.",
      author: "Gandhi",
    },
    { text: "La vie est un art, il faut la peindre avec les couleurs de l'âme.", author: "Vincent Van Gogh" },
    { text: "Le bonheur est une fleur qu'il ne faut pas cueillir.", author: "André Gide" },
    { text: "La vie est un rêve, réveille-toi.", author: "Proverbe chinois" },
    { text: "Le savoir est une arme.", author: "Francis Bacon" },
    { text: "La vérité est une, mais les chemins pour y arriver sont multiples.", author: "Gandhi" },
    { text: "Le doute est le commencement de la sagesse.", author: "Aristote" },
    { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
    {
      text: "Le bonheur est souvent la seule chose que l'on puisse donner sans l'avoir et c'est en le donnant qu'on l'acquiert.",
      author: "Voltaire",
    },
    { text: "La seule façon de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès.", author: "Albert Schweitzer" },
    { text: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
    {
      text: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.",
      author: "Albert Einstein",
    },
    { text: "Le monde est un livre et ceux qui ne voyagent pas n'en lisent qu'une page.", author: "Saint Augustin" },
    { text: "La vie est une aventure audacieuse ou rien du tout.", author: "Helen Keller" },
    {
      text: "Le plus grand plaisir dans la vie est de faire ce que les gens disent que vous ne pouvez pas faire.",
      author: "Walter Bagehot",
    },
    { text: "La persévérance est la clé du succès.", author: "Confucius" },
    { text: "Le bonheur est une direction, pas une destination.", author: "Zig Ziglar" },
    {
      text: "La vie est courte, brisez les règles, pardonnez vite, embrassez lentement, aimez vraiment, riez sans contrôle et ne regrettez jamais rien qui vous ait fait sourire.",
      author: "Mark Twain",
    },
    { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
    {
      text: "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui.",
      author: "Franklin D. Roosevelt",
    },
    { text: "Le meilleur moyen de prédire l'avenir est de le créer.", author: "Peter Drucker" },
    {
      text: "La vie est un cadeau, et elle nous offre le privilège, l'opportunité et la responsabilité de donner quelque chose en retour en devenant plus.",
      author: "Tony Robbins",
    },
    { text: "La sagesse commence dans l'émerveillement.", author: "Socrate" },
    { text: "Le bonheur est une habitude, cultivez-le.", author: "Elbert Hubbard" },
    { text: "La vie est un long apprentissage de la perte.", author: "Jean Cocteau" },
    { text: "Le but de la vie est de vivre, et de vivre pleinement.", author: "Jack London" },
    { text: "La beauté est dans les yeux de celui qui regarde.", author: "Margaret Wolfe Hungerford" },
    { text: "Le silence est d'or.", author: "Proverbe" },
    { text: "La patience est amère, mais son fruit est doux.", author: "Jean-Jacques Rousseau" },
    { text: "Le temps est un grand maître, dit-on, le malheur est qu'il tue ses élèves.", author: "Hector Berlioz" },
    { text: "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", author: "Mère Teresa" },
    {
      text: "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.",
      author: "Gandhi",
    },
    { text: "La vie est un art, il faut la peindre avec les couleurs de l'âme.", author: "Vincent Van Gogh" },
    { text: "Le bonheur est une fleur qu'il ne faut pas cueillir.", author: "André Gide" },
    { text: "La vie est un rêve, réveille-toi.", author: "Proverbe chinois" },
    { text: "Le savoir est une arme.", author: "Francis Bacon" },
    { text: "La vérité est une, mais les chemins pour y arriver sont multiples.", author: "Gandhi" },
    { text: "La mélancolie, c'est le bonheur d'être triste.", author: "Victor Hugo" },  
{ text: "L'avenir, c'est l'ombre que le présent projette sur l'avenir.", author: "Victor Hugo" },  
{ text: "La musique exprime ce qui ne peut être dit et sur quoi il est impossible de taire.", author: "Victor Hugo" },  
{ text: "La vie est une fleur dont l'amour est le miel.", author: "Victor Hugo" },  
{ text: "La liberté commence où l'ignorance finit.", author: "Victor Hugo" },  
{ text: "Au milieu de l'hiver, j'ai découvert en moi un invincible été.", author: "Albert Camus" },  
{ text: "L'absurde naît de cette confrontation entre l'appel humain et le silence déraisonnable du monde.", author: "Albert Camus" },  
{ text: "Il n'y a pas de honte à préférer le bonheur.", author: "Albert Camus" },  
{ text: "La vérité, comme la lumière, aveugle.", author: "Albert Camus" },  
{ text: "Créer, c'est vivre deux fois.", author: "Albert Camus" },  
{ text: "On ne guérit jamais d'une enfance blessée.", author: "Yasmina Khadra" },  
{ text: "L'espoir est la seule chose qui nous reste quand tout est perdu.", author: "Yasmina Khadra" },  
{ text: "La peur est une prison où l'on s'enferme soi-même.", author: "Yasmina Khadra" },  
{ text: "L'amour est le seul luxe qui ne coûte rien.", author: "Yasmina Khadra" },  
{ text: "La vie est un roman dont nous sommes à la fois l'auteur et le personnage.", author: "Yasmina Khadra" },  
{ text: "Si vous demandez ce que je viens faire en ce monde, je vous répondrai : je viens vivre tout haut.", author: "Émile Zola" },  
{ text: "La vérité est en marche, et rien ne l'arrêtera.", author: "Émile Zola" },  
{ text: "L'art est un coin de la création vu à travers un tempérament.", author: "Émile Zola" },  
{ text: "On ne peut pas vivre sans amour, sans passion, sans quelque folie.", author: "Émile Zola" },  
{ text: "Le bonheur n'est que dans la réalisation de soi.", author: "Émile Zola" },  
{ text: "Je pense, donc je suis.", author: "René Descartes" },  
{ text: "Le bon sens est la chose du monde la mieux partagée.", author: "René Descartes" },  
{ text: "Douter de tout ou tout croire, ce sont deux solutions également commodes.", author: "René Descartes" },  
{ text: "La lecture de tous les bons livres est comme une conversation avec les plus honnêtes gens des siècles passés.", author: "René Descartes" },  
{ text: "L'âme est plus facile à connaître que le corps.", author: "René Descartes" },  
{ text: "La douleur est un lieu obscur où l'on apprend à voir.", author: "Marguerite Yourcenar" },  
{ text: "Le vrai lieu de naissance est celui où l'on a porté pour la première fois un regard intelligent sur soi-même.", author: "Marguerite Yourcenar" },  
{ text: "La vie est un sommeil, l'amour en est le rêve.", author: "Marguerite Yourcenar" },  
{ text: "La liberté n'est pas un don, mais une conquête.", author: "Marguerite Yourcenar" },  
{ text: "On ne possède que ce que l'on donne.", author: "Marguerite Yourcenar" },  
{ text: "La musique souvent me prend comme une mer.", author: "Charles Baudelaire" },  
{ text: "Le beau est toujours bizarre.", author: "Charles Baudelaire" },  
{ text: "La plus belle des ruses du diable est de vous persuader qu'il n'existe pas.", author: "Charles Baudelaire" },  
{ text: "La volupté unique et suprême de l'amour gît dans la certitude de faire le mal.", author: "Charles Baudelaire" },  
{ text: "Je suis un cimetière abhorré de la lune.", author: "Charles Baudelaire" },  
{ text: "On ne naît pas femme, on le devient.", author: "Simone de Beauvoir" },  
{ text: "La liberté, c'est de pouvoir choisir sa propre vie.", author: "Simone de Beauvoir" },  
{ text: "Rien n'est plus dangereux que la certitude d'avoir raison.", author: "Simone de Beauvoir" },  
{ text: "La vieillesse est un naufrage.", author: "Simone de Beauvoir" },  
{ text: "L'écriture est une façon de dire non à la mort.", author: "Simone de Beauvoir" },  
{ text: "Le silence est le cri le plus puissant.", author: "Anonyme" },  
{ text: "L'amour est la seule folie qui justifie la vie.", author: "Anonyme" },  
{ text: "Chaque larme est une histoire non racontée.", author: "Anonyme" },  
{ text: "La solitude est le miroir où l'âme se regarde.", author: "Anonyme" },  
{ text: "La vie n'est qu'une ombre qui passe, mais l'amour est la lumière qui demeure.", author: "Anonyme" },  
  ],
  it: [
    { text: "La semplicità è l'ultima sofisticazione.", author: "Leonardo da Vinci" },
    { text: "Chi non risica, non rosica.", author: "Proverbio italiano" },
    {
      text: "L'arte dice l'indicibile; esprime l'inesprimibile, traduce l'intraducibile.",
      author: "Leonardo da Vinci",
    },
    {
      text: "Non si può insegnare niente a un uomo; si può solo aiutarlo a trovare la risposta dentro di sé.",
      author: "Galileo Galilei",
    },
    {
      text: "La vita è come andare in bicicletta: per mantenere l'equilibrio devi muoverti.",
      author: "Albert Einstein",
    },
    { text: "Il tempo è la cosa più preziosa che possiamo spendere.", author: "Teofrasto" },
    { text: "Chi ha pazienza può ottenere ciò che vuole.", author: "Benjamin Franklin" },
    { text: "La felicità non è avere quello che si desidera, ma desiderare quello che si ha.", author: "Oscar Wilde" },
    { text: "Ogni grande viaggio inizia con un piccolo passo.", author: "Lao Tzu" },
    {
      text: "La cultura è l'unico bene dell'umanità che, diviso fra tutti, anziché diminuire diventa più grande.",
      author: "Hans Georg Gadamer",
    },
    { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
    { text: "Non è mai troppo tardi per essere quello che avresti potuto essere.", author: "George Eliot" },
    { text: "La vita è troppo importante per essere presa sul serio.", author: "Oscar Wilde" },
    { text: "L'immaginazione è più importante della conoscenza.", author: "Albert Einstein" },
    {
      text: "Il coraggio non è l'assenza di paura, ma la capacità di vincere ciò che fa paura.",
      author: "Nelson Mandela",
    },
    { text: "È meglio fare che dire, è meglio agire che lamentarsi.", author: "Winston Churchill" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "Non è la montagna che conquistiamo, ma noi stessi.", author: "Sir Edmund Hillary" },
    {
      text: "La differenza tra l'ordinario e lo straordinario è quel piccolo qualcosa in più.",
      author: "Jimmy Johnson",
    },
    {
      text: "Il successo è andare di fallimento in fallimento senza perdere l'entusiasmo.",
      author: "Winston Churchill",
    },
    {
      text: "La più grande rivoluzione della nostra generazione è la scoperta che l'essere umano può cambiare la sua vita.",
      author: "William James",
    },
    { text: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Gandhi" },
    { text: "L'educazione è l'arma più potente che puoi usare per cambiare il mondo.", author: "Nelson Mandela" },
    { text: "Bisogna sempre puntare alla luna, perché anche se sbagli, atterri tra le stelle.", author: "Oscar Wilde" },
    { text: "La saggezza è avere sogni abbastanza grandi da non perderli di vista.", author: "Oscar Wilde" },
    { text: "Ogni esperto è stato una volta un principiante.", author: "Helen Hayes" },
    { text: "Il dubbio è l'inizio della saggezza.", author: "Aristotele" },
    { text: "La vita è un mistero da vivere, non un problema da risolvere.", author: "Gandhi" },
    {
      text: "La felicità è spesso l'unica cosa che si può dare senza averla, ed è dandola che la si acquista.",
      author: "Voltaire",
    },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    {
      text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.",
      author: "Albert Schweitzer",
    },
    { text: "La semplicità è la massima sofisticazione.", author: "Leonardo da Vinci" },
    {
      text: "La conoscenza si acquisisce con l'esperienza, tutto il resto è solo informazione.",
      author: "Albert Einstein",
    },
    { text: "Il mondo è un libro e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "La vita è un'avventura audace o niente affatto.", author: "Helen Keller" },
    {
      text: "Il più grande piacere della vita è fare ciò che la gente dice che non puoi fare.",
      author: "Walter Bagehot",
    },
    { text: "La perseveranza è la chiave del successo.", author: "Confucio" },
    { text: "La felicità è una direzione, non una destinazione.", author: "Zig Ziglar" },
    {
      text: "La vita è breve, rompi le regole, perdona in fretta, bacia lentamente, ama veramente, ridi senza controllo e non rimpiangere mai nulla che ti abbia fatto sorridere.",
      author: "Mark Twain",
    },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    {
      text: "L'unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi.",
      author: "Franklin D. Roosevelt",
    },
    { text: "Il modo migliore per prevedere il futuro è crearlo.", author: "Peter Drucker" },
    {
      text: "La vita è un dono, e ci offre il privilegio, l'opportunità e la responsabilità di restituire qualcosa diventando di più.",
      author: "Tony Robbins",
    },
    { text: "La saggezza inizia nella meraviglia.", author: "Socrate" },
    { text: "La felicità è un'abitudine, coltivala.", author: "Elbert Hubbard" },
    { text: "La vita è un lungo apprendimento della perdita.", author: "Jean Cocteau" },
    { text: "Lo scopo della vita è vivere, e vivere pienamente.", author: "Jack London" },
    { text: "La bellezza è negli occhi di chi guarda.", author: "Margaret Wolfe Hungerford" },
    { text: "Il silenzio è d'oro.", author: "Proverbio" },
    { text: "La pazienza è amara, ma il suo frutto è dolce.", author: "Jean-Jacques Rousseau" },
    { text: "Il tempo è un grande maestro, si dice, il guaio è che uccide i suoi allievi.", author: "Hector Berlioz" },
    {
      text: "La vita è una sfida da affrontare, una felicità da meritare, un'avventura da tentare.",
      author: "Madre Teresa",
    },
    {
      text: "Il più grande viaggiatore non è colui che ha fatto dieci volte il giro del mondo, ma colui che ha fatto una sola volta il giro di se stesso.",
      author: "Gandhi",
    },
    { text: "La vita è un'arte, bisogna dipingerla con i colori dell'anima.", author: "Vincent Van Gogh" },
    { text: "La felicità è un fiore che non bisogna cogliere.", author: "André Gide" },
    { text: "La vita è un sogno, svegliati.", author: "Proverbio cinese" },
    { text: "La conoscenza è un'arma.", author: "Francis Bacon" },
    { text: "La verità è una, ma i sentieri per raggiungerla sono molteplici.", author: "Gandhi" },
    { text: "Il dubbio è l'inizio della saggezza.", author: "Aristotele" },
    { text: "La vita è un mistero da vivere, non un problema da risolvere.", author: "Gandhi" },
    {
      text: "La felicità è spesso l'unica cosa che si può dare senza averla, ed è dandola che la si acquista.",
      author: "Voltaire",
    },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    {
      text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.",
      author: "Albert Schweitzer",
    },
    { text: "La semplicità è la massima sofisticazione.", author: "Leonardo da Vinci" },
    {
      text: "La conoscenza si acquisisce con l'esperienza, tutto il resto è solo informazione.",
      author: "Albert Einstein",
    },
    { text: "Il mondo è un libro e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "La vita è un'avventura audace o niente affatto.", author: "Helen Keller" },
    {
      text: "Il più grande piacere della vita è fare ciò che la gente dice che non puoi fare.",
      author: "Walter Bagehot",
    },
    { text: "La perseveranza è la chiave del successo.", author: "Confucio" },
    { text: "La felicità è una direzione, non una destinazione.", author: "Zig Ziglar" },
    {
      text: "La vita è breve, rompi le regole, perdona in fretta, bacia lentamente, ama veramente, ridi senza controllo e non rimpiangere mai nulla che ti abbia fatto sorridere.",
      author: "Mark Twain",
    },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    {
      text: "L'unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi.",
      author: "Franklin D. Roosevelt",
    },
    { text: "Il modo migliore per prevedere il futuro è crearlo.", author: "Peter Drucker" },
    {
      text: "La vita è un dono, e ci offre il privilegio, l'opportunità e la responsabilità di restituire qualcosa diventando di più.",
      author: "Tony Robbins",
    },
    { text: "La saggezza inizia nella meraviglia.", author: "Socrate" },
    { text: "La felicità è un'abitudine, coltivala.", author: "Elbert Hubbard" },
    { text: "La vita è un lungo apprendimento della perdita.", author: "Jean Cocteau" },
    { text: "Lo scopo della vita è vivere, e vivere pienamente.", author: "Jack London" },
    { text: "La bellezza è negli occhi di chi guarda.", author: "Margaret Wolfe Hungerford" },
    { text: "Il silenzio è d'oro.", author: "Proverbio" },
    { text: "La pazienza è amara, ma il suo frutto è dolce.", author: "Jean-Jacques Rousseau" },
    { text: "Il tempo è un grande maestro, si dice, il guaio è che uccide i suoi allievi.", author: "Hector Berlioz" },
    {
      text: "La vita è una sfida da affrontare, una felicità da meritare, un'avventura da tentare.",
      author: "Madre Teresa",
    },
    {
      text: "Il più grande viaggiatore non è colui che ha fatto dieci volte il giro del mondo, ma colui che ha fatto una sola volta il giro di se stesso.",
      author: "Gandhi",
    },
    { text: "La vita è un'arte, bisogna dipingerla con i colori dell'anima.", author: "Vincent Van Gogh" },
    { text: "La felicità è un fiore che non bisogna cogliere.", author: "André Gide" },
    { text: "La vita è un sogno, svegliati.", author: "Proverbio cinese" },
    { text: "La conoscenza è un'arma.", author: "Francis Bacon" },
    { text: "La verità è una, ma i sentieri per raggiungerla sono molteplici.", author: "Gandhi" },
    { text: "L'amor che move il sole e l'altre stelle.", author: "Dante Alighieri" },  
{ text: "Lasciate ogne speranza, voi ch'intrate.", author: "Dante Alighieri" },  
{ text: "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.", author: "Dante Alighieri" },  
{ text: "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.", author: "Dante Alighieri" },  
{ text: "L’amore e ’l cor gentil sono una cosa.", author: "Dante Alighieri" },  
{ text: "Il naufragar m'è dolce in questo mare.", author: "Giacomo Leopardi" },  
{ text: "Sempre caro mi fu quest'ermo colle.", author: "Giacomo Leopardi" },  
{ text: "La vita è un brivido che scorre tra due nulla.", author: "Giacomo Leopardi" },  
{ text: "Il mondo è un nulla, e l’uomo è un’ombra.", author: "Giacomo Leopardi" },  
{ text: "Tutto è male, e il meglio è non essere.", author: "Giacomo Leopardi" },  
{ text: "Così è (se vi pare).", author: "Luigi Pirandello" },  
{ text: "Uno, nessuno e centomila.", author: "Luigi Pirandello" },  
{ text: "La follia è l’unico modo per sopravvivere alla realtà.", author: "Luigi Pirandello" },  
{ text: "La verità è figlia del tempo, non dell’autorità.", author: "Luigi Pirandello" },  
{ text: "Ognuno di noi ha dentro di sé un intero mondo sconosciuto.", author: "Luigi Pirandello" },  
{ text: "Spesso il male di vivere ho incontrato.", author: "Eugenio Montale" },  
{ text: "Codesto solo oggi possiamo dirti: ciò che non siamo, ciò che non vogliamo.", author: "Eugenio Montale" },  
{ text: "La vita è questo scialo di triti fatti.", author: "Eugenio Montale" },  
{ text: "Forse un mattino andando in un’aria di vetro.", author: "Eugenio Montale" },  
{ text: "La speranza è l’ultima a morire, ma muore.", author: "Eugenio Montale" },  
{ text: "La solitudine è la mia compagna fedele.", author: "Umberto Saba" },  
{ text: "Amo la vita, anche se mi fa male.", author: "Umberto Saba" },  
{ text: "La poesia è un grido disperato di gioia.", author: "Umberto Saba" },  
{ text: "Nessuno sa di sé quel che sa l’anima.", author: "Umberto Saba" },  
{ text: "Il dolore è la mia patria.", author: "Umberto Saba" },  
{ text: "La follia è una condizione umana.", author: "Alda Merini" },  
{ text: "Sono nata il ventuno a primavera.", author: "Alda Merini" },  
{ text: "La poesia è la voce dell’anima.", author: "Alda Merini" },  
{ text: "Il dolore è il mio pane quotidiano.", author: "Alda Merini" },  
{ text: "L’amore è l’unica follia che vale la pena vivere.", author: "Alda Merini" },  
{ text: "L’universo è infinito, perché è la manifestazione di un Dio infinito.", author: "Giordano Bruno" },  
{ text: "La verità è figlia del tempo.", author: "Giordano Bruno" },  
{ text: "Non c’è nulla di più pericoloso di un’idea quando ne hai una sola.", author: "Giordano Bruno" },  
{ text: "L’anima non muore, ma si trasforma.", author: "Giordano Bruno" },  
{ text: "Chi cerca la verità deve dubitare di tutto.", author: "Giordano Bruno" },  
{ text: "Il silenzio è l’urlo più forte.", author: "Anonimo" },  
{ text: "Vivere è navigare in un mare di domande senza risposte.", author: "Anonimo" },  
{ text: "L’amore è l’unica luce che non teme l’oscurità.", author: "Anonimo" },  
{ text: "La morte non è la fine, ma solo un cambio di abito.", author: "Anonimo" },  
{ text: "Ogni lacrima è una poesia non scritta.", author: "Anonimo" },  
  ],
  es: [
    { text: "No hay camino para la paz, la paz es el camino.", author: "Gandhi" },
    {
      text: "La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.",
      author: "John Lennon",
    },
    { text: "Solo sé que no sé nada.", author: "Sócrates" },
    { text: "El que no arriesga no gana.", author: "Refrán español" },
    { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
    { text: "No dejes para mañana lo que puedas hacer hoy.", author: "Benjamin Franklin" },
    { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
    { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
    { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "La vida es 10% lo que te sucede y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
    { text: "El futuro pertenece a aquellos que creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
    { text: "Nunca es demasiado tarde para ser lo que podrías haber sido.", author: "George Eliot" },
    { text: "La vida es demasiado importante para tomarla en serio.", author: "Oscar Wilde" },
    {
      text: "El coraje no es la ausencia de miedo, sino la capacidad de vencer lo que da miedo.",
      author: "Nelson Mandela",
    },
    { text: "Es mejor hacer que decir, es mejor actuar que quejarse.", author: "Winston Churchill" },
    { text: "No es la montaña lo que conquistamos, sino a nosotros mismos.", author: "Sir Edmund Hillary" },
    { text: "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.", author: "Jimmy Johnson" },
    {
      text: "La mayor revolución de nuestra generación es el descubrimiento de que el ser humano puede cambiar su vida.",
      author: "William James",
    },
    { text: "Sé el cambio que quieres ver en el mundo.", author: "Gandhi" },
    { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
    {
      text: "Siempre apunta a la luna, porque incluso si fallas, aterrizarás entre las estrellas.",
      author: "Oscar Wilde",
    },
    {
      text: "La sabiduría es tener sueños lo suficientemente grandes como para no perderlos de vista.",
      author: "Oscar Wilde",
    },
    { text: "Todo experto fue una vez un principiante.", author: "Helen Hayes" },
    { text: "La mejor manera de empezar es dejar de hablar y empezar a hacer.", author: "Walt Disney" },
    { text: "No dejes que el ayer ocupe demasiado espacio del hoy.", author: "Will Rogers" },
    { text: "Aprendes más del fracaso que del éxito.", author: "Desconocido" },
    {
      text: "Si estás trabajando en algo emocionante que realmente te importa, no tienes que ser empujado.",
      author: "Steve Jobs",
    },
    {
      text: "El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta.",
      author: "Winston Churchill",
    },
    { text: "Es mejor fallar en originalidad que tener éxito en imitación.", author: "Herman Melville" },
    { text: "El camino al éxito y el camino al fracaso son casi exactamente el mismo.", author: "Colin R. Davis" },
    { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
    { text: "La vida es un misterio que hay que vivir, no un problema que resolver.", author: "Gandhi" },
    {
      text: "La felicidad es a menudo lo único que puedes dar sin tenerla, y es dándola como la adquieres.",
      author: "Voltaire",
    },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    {
      text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
      author: "Albert Schweitzer",
    },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    {
      text: "El conocimiento se adquiere por la experiencia, todo lo demás es solo información.",
      author: "Albert Einstein",
    },
    { text: "El mundo es un libro y aquellos que no viajan solo leen una página.", author: "San Agustín" },
    { text: "La vida es una aventura atrevida o nada en absoluto.", author: "Helen Keller" },
    { text: "El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer.", author: "Walter Bagehot" },
    { text: "La perseverancia es la clave del éxito.", author: "Confucio" },
    { text: "La felicidad es una dirección, no un destino.", author: "Zig Ziglar" },
    {
      text: "La vida es corta, rompe las reglas, perdona rápido, besa despacio, ama de verdad, ríe sin control y nunca te arrepientas de nada que te haya hecho sonreír.",
      author: "Mark Twain",
    },
    { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
    {
      text: "El único límite a nuestra realización del mañana serán nuestras dudas de hoy.",
      author: "Franklin D. Roosevelt",
    },
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    {
      text: "La vida es un regalo, y nos ofrece el privilegio, la oportunidad y la responsabilidad de devolver algo al convertirnos en más.",
      author: "Tony Robbins",
    },
    { text: "La sabiduría comienza en el asombro.", author: "Sócrates" },
    { text: "La felicidad es un hábito, cultívalo.", author: "Elbert Hubbard" },
    { text: "La vida es un largo aprendizaje de la pérdida.", author: "Jean Cocteau" },
    { text: "El propósito de la vida es vivir, y vivir plenamente.", author: "Jack London" },
    { text: "La belleza está en los ojos del que mira.", author: "Margaret Wolfe Hungerford" },
    { text: "El silencio es oro.", author: "Proverbio" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "El tiempo es un gran maestro, se dice, el problema es que mata a sus alumnos.", author: "Hector Berlioz" },
    {
      text: "La vida es un desafío que afrontar, una felicidad que merecer, una aventura que intentar.",
      author: "Madre Teresa",
    },
    {
      text: "El mayor viajero no es el que ha dado diez veces la vuelta al mundo, sino el que ha dado una sola vez la vuelta a sí mismo.",
      author: "Gandhi",
    },
    { text: "La vida es un arte, hay que pintarla con los colores del alma.", author: "Vincent Van Gogh" },
    { text: "La felicidad es una flor que no hay que coger.", author: "André Gide" },
    { text: "La vida es un sueño, despierta.", author: "Proverbio chino" },
    { text: "El conocimiento es un arma.", author: "Francis Bacon" },
    { text: "La verdad es una, pero los caminos para llegar a ella son múltiples.", author: "Gandhi" },
    { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
    { text: "La vida es un misterio que hay que vivir, no un problema que resolver.", author: "Gandhi" },
    {
      text: "La felicidad es a menudo lo único que puedes dar sin tenerla, y es dándola como la adquieres.",
      author: "Voltaire",
    },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    {
      text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
      author: "Albert Schweitzer",
    },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    {
      text: "El conocimiento se adquiere por la experiencia, todo lo demás es solo información.",
      author: "Albert Einstein",
    },
    { text: "El mundo es un libro y aquellos que no viajan solo leen una página.", author: "San Agustín" },
    { text: "La vida es una aventura atrevida o nada en absoluto.", author: "Helen Keller" },
    { text: "El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer.", author: "Walter Bagehot" },
    { text: "La perseverancia es la clave del éxito.", author: "Confucio" },
    { text: "La felicidad es una dirección, no un destino.", author: "Zig Ziglar" },
    {
      text: "La vida es corta, rompe las reglas, perdona rápido, besa despacio, ama de verdad, ríe sin control y nunca te arrepientas de nada que te haya hecho sonreír.",
      author: "Mark Twain",
    },
    { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
    {
      text: "El único límite a nuestra realización del mañana serán nuestras dudas de hoy.",
      author: "Franklin D. Roosevelt",
    },
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    {
      text: "La vida es un regalo, y nos ofrece el privilegio, la oportunidad y la responsabilidad de devolver algo al convertirnos en más.",
      author: "Tony Robbins",
    },
    { text: "La sabiduría comienza en el asombro.", author: "Sócrates" },
    { text: "La felicidad es un hábito, cultívalo.", author: "Elbert Hubbard" },
    { text: "La vida es un largo aprendizaje de la pérdida.", author: "Jean Cocteau" },
    { text: "El propósito de la vida es vivir, y vivir plenamente.", author: "Jack London" },
    { text: "La belleza está en los ojos del que mira.", author: "Margaret Wolfe Hungerford" },
    { text: "El silencio es oro.", author: "Proverbio" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "El tiempo es un gran maestro, se dice, el problema es que mata a sus alumnos.", author: "Hector Berlioz" },
    {
      text: "La vida es un desafío que afrontar, una felicidad que merecer, una aventura que intentar.",
      author: "Madre Teresa",
    },
    {
      text: "El mayor viajero no es el que ha dado diez veces la vuelta al mundo, sino el que ha dado una sola vez la vuelta a sí mismo.",
      author: "Gandhi",
    },
    { text: "La vida es un arte, hay que pintarla con los colores del alma.", author: "Vincent Van Gogh" },
    { text: "La felicidad es una flor que no hay que coger.", author: "André Gide" },
    { text: "La vida es un sueño, despierta.", author: "Proverbio chino" },
    { text: "El conocimiento es un arma.", author: "Francis Bacon" },
    { text: "La verdad es una, pero los caminos para llegar a ella son múltiples.", author: "Gandhi" },
  ],
  ar: [
    { text: "اعرف نفسك تعرف ربك", author: "مثل عربي" },
    { text: "خير الناس أنفعهم للناس", author: "حديث شريف" }, 
    { text: "إنما الأعمال بالنيات", author: "حديث شريف" },
    { text: "من صبر ظفر", author: "مثل عربي" },
    { text: "الحكمة ضالة المؤمن", author: "حديث شريف" },
    { text: "من تواضع لله رفعه", author: "حديث شريف" },
    { text: "الدنيا دار ممر والآخرة دار مقر", author: "حكمة إسلامية" },
    { text: "ليس الغنى عن كثرة العرض ولكن الغنى غنى النفس", author: "حديث شريف" },
    { text: "المؤمن مرآة أخيه", author: "حديث شريف" },
    { text: "من لم يشكر الناس لم يشكر الله", author: "حديث شريف" },
    { text: "اعمل لدنياك كأنك تعيش أبداً واعمل لآخرتك كأنك تموت غداً", author: "علي بن أبي طالب" },
    { text: "الحياة مدرسة والتجارب معلمها", author: "حكمة عربية" },
    { text: "من أراد أن يطاع في المستحيل فليترك الممكن", author: "حكمة عربية" },
    { text: "العبرة بالخواتيم", author: "مثل عربي" },
    { text: "الحق أبلج والباطل لجلج", author: "مثل عربي" },
    { text: "من أعان ظالماً سلطه الله عليه", author: "حديث شريف" },
    { text: "الناس معادن كمعادن الذهب والفضة", author: "حديث شريف" },
    { text: "إذا أردت أن تطاع فأمر بما يستطاع", author: "حكمة عربية" },
    { text: "لا تكن ليناً فتعصر، ولا قاسياً فتكسر.", author: "مثل عربي" },
    { text: "كل إناء بما فيه ينضح.", author: "مثل عربي" },
    { text: "لا تحقرن من المعروف شيئاً.", author: "حديث شريف" },
    { text: "ما خاب من استخار ولا ندم من استشار.", author: "مثل عربي" },
    { text: "المرء على دين خليله فلينظر أحدكم من يخالل.", author: "حديث شريف" },
    { text: "لا ييأس من روح الله إلا القوم الكافرون.", author: "القرآن الكريم" },
    { text: "إن مع العسر يسرا.", author: "القرآن الكريم" },
    { text: "لا تحزن إن الله معنا.", author: "القرآن الكريم" },
    { text: "لا تكن كمن يجمع الحطب ليحرق نفسه.", author: "مثل عربي" },
    { text: "إذا لم تكن ذئباً أكلتك الذئاب.", author: "مثل عربي" },
    { text: "من شب على شيء شاب عليه.", author: "مثل عربي" },
    { text: "لا تلوموا الناس ولكن لوموا أنفسكم.", author: "مثل عربي" },
    { text: "المرء حيث يضع نفسه.", author: "مثل عربي" },
    { text: "إنما الأمم الأخلاق ما بقيت فإن هم ذهبت أخلاقهم ذهبوا.", author: "أحمد شوقي" },
    { text: "إذا الشعب يوماً أراد الحياة فلا بد أن يستجيب القدر.", author: "أبو القاسم الشابي" },
    { text: "أنا لا أكتب إلا لأني أحب أن أكتب، ولأني لا أستطيع أن أعيش بدون أن أكتب.", author: "محمود درويش" },
    { text: "على هذه الأرض ما يستحق الحياة.", author: "محمود درويش" },
    { text: "فكر بغيرك.", author: "محمود درويش" },
    { text: "أنا من هناك، أنا من هنا، ولست هناك، ولست هنا.", author: "محمود درويش" },
    { text: "لا تسألني عن الحب، بل اسألني عن قلبي.", author: "محمود درويش" },
    { text: "الآن، بعد أن أصبحتُ رجلاً، أرى أن الطفولة كانت أجمل.", author: "محمود درويش" },
    { text: "الروح لا تطلب شيئاً إلا الحب، والحب لا يطلب شيئاً إلا أن يكون هو كل شيء.", author: "جلال الدين الرومي" },
    { text: "ما تبحث عنه يبحث عنك.", author: "جلال الدين الرومي" },
    { text: "لا تكن بلا حب، لئلا تشعر بأنك ميت.", author: "جلال الدين الرومي" },
    { text: "أنت لست قطرة في محيط، أنت المحيط كله في قطرة.", author: "جلال الدين الرومي" },
    { text: "دع جمال ما تحب يكون ما تفعله.", author: "جلال الدين الرومي" },
    { text: "هناك صوت لا يستخدم الكلمات. استمع إليه.", author: "جلال الدين الرومي" },
    { text: "الحب هو الجسر بينك وبين كل شيء.", author: "جلال الدين الرومي" },
    { text: "لا تحزن. أي شيء تفقده سيعود إليك بشكل آخر.", author: "جلال الدين الرومي" },
    { text: "الكون كله موجود في داخلك. اسأل نفسك كل شيء.", author: "جلال الدين الرومي" },
    { text: "القلب هو عين الروح.", author: "جلال الدين الرومي" },
   { text: "إذا غامَرْتَ في شَرَفٍ مَرُومِ فلا تَقنَعْ بما دونَ النُّجُومِ.", author: "المتنبي" },  
{ text: "الظَّلْمُ مِن شِيَمِ النُّفُوسِ، فإن تَجِدْ ذَا عِفَّةٍ فَلِعِلَّةٍ لا يَظْلِمُ.", author: "ابن خلدون" },  
{ text: "النَّاسُ أَعْدَاءُ مَا جَهِلُوا.", author: "علي بن أبي طالب" },  
{ text: "لَيْسَ الْفَقْرُ أَنْ لا تَمْلِكَ دِرْهَمًا، الْفَقْرُ أَنْ لا تَكُونَ لَكَ قِيمَةٌ.", author: "عمر بن الخطاب" },  
{ text: "الحياةُ لا تُفْهَمُ إِلَّا إِلَى الْوَرَاءِ، وَلَكِنْ يَجِبُ أَنْ تُعَاشَ إِلَى الأَمَامِ.", author: "جبران خليل جبران" },  
{ text: "لَوْ كَانَ الْجَهْلُ رَجُلًا لَقَتَلْتُهُ.", author: "علي بن أبي طالب" },  
{ text: "الْكِتَابُ خَيْرُ جَلِيسٍ فِي الزَّمَانِ.", author: "المتنبي" },    
{ text: "مَنْ لا يَعْرِفُ الصَّبْرَ لا يَعْرِفُ النَّجَاحَ.", author: "نجيب محفوظ" },  
{ text: "الْحُرِّيَّةُ هِيَ الْحَيَاةُ، وَلَكِنْ لا حُرِّيَّةَ بِلا فَضِيلَةٍ.", author: "أحمد شوقي" },    
{ text: "الْقُلُوبُ أَوْعِيَةٌ وَالشِّفَاهُ أَقْفَالُهَا وَالأَلْسُنُ مَفَاتِيحُهَا، فَلْيَحْفَظْ كُلٌّ مِنَّا مِفْتَاحَ سِرِّهِ.", author: "ابن سينا" },  
{ text: "الرَّاحَةُ تُولِدُ الرُّكُودَ، وَالتَّعَبُ يُولِدُ الْعَظَمَةَ.", author: "طه حسين" },  
{ text: "الْخَوْفُ مِنَ الْمَوْتِ خَوْفٌ مِنَ الْحَيَاةِ نَفْسِهَا.", author: "ميخائيل نعيمة" },  
{ text: "الْحِكْمَةُ ضَالَّةُ الْمُؤْمِنِ، فَحَيْثُ وَجَدَهَا فَهُوَ أَحَقُّ بِهَا.", author: "علي بن أبي طالب" },  
{ text: "إِذَا كَانَ الْكَلامُ مِنْ فِضَّةٍ، فَالسُّكُوتُ مِنْ ذَهَبٍ.", author: "علي بن أبي طالب" },  
{ text: "الْإِنْسَانُ عَدُوُّ مَا جَهِلَ.", author: "ابن خلدون" },  
{ text: "الْحُبُّ هُوَ النُّورُ الَّذِي يُضِيءُ الْكَوْنَ.", author: "جبران خليل جبران" },  
{ text: "الْعَيْنُ لا تَرَى الذَّاتَ إِلَّا بِالْمِرْآةِ، وَالرُّوحُ لا تَرَى نَفْسَهَا إِلَّا فِي الْحُبِّ.", author: "جبران خليل جبران" },  
{ text: "لَيْسَ الْجَمَالُ بِأَثْوَابٍ تُزَيِّنُنَا، إِنَّ الْجَمَالَ جَمَالُ الْعِلْمِ وَالْأَدَبِ.", author: "أحمد شوقي" },  
{ text: "الْحَقُّ يُقَالُ وَلَوْ كَانَ مُرًّا.", author: "عمر بن الخطاب" },
{ text: "الحب لا يعطي إلا نفسه، ولا يأخذ إلا من نفسه.", author: "جبران خليل جبران" },  
{ text: "الصمت أبلغ من الكلام، لأن الصمت لا يكذب.", author: "جبران خليل جبران" },  
{ text: "أنت أعمق مما نزلت إليه نفسي، وأعلى مما نهضت إليه روحي.", author: "جبران خليل جبران" },  
{ text: "في قلب كل شتاء ربيع نابض، ووراء كل ليل فجر باسم.", author: "جبران خليل جبران" },  
{ text: "الحياة ليست إلا ظلًا زائلًا، إلا إذا أحببت.", author: "جبران خليل جبران" },  
{ text: "أنت نصفي الذي كنتُ أبحث عنه، والنصف الذي لم أكن أعرف أني افتقدته.", author: "جبران خليل جبران" },  
{ text: "القلوب المتوضعة بالحب لا تموت أبدًا.", author: "جبران خليل جبران" },  
{ text: "لا تستطيع أن تضحك وتكون قاسيًا في نفس اللحظة.", author: "جبران خليل جبران" },  
{ text: "الوحدة حكمة، والجماعة قوة، والحب سلام.", author: "جبران خليل جبران" },  
{ text: "الموت ليس إلا أن نخلع ثوبًا قديمًا لنلبس آخر جديدًا.", author: "جبران خليل جبران" },  
{ text: "الحياة ليست سوى ومضة، فاجعلها ومضة نور.", author: "ميخائيل نعيمة" },  
{ text: "الروح لا تموت، بل تخلع ثوبًا باليًا لترتدي ثوبًا جديدًا.", author: "ميخائيل نعيمة" },  
{ text: "كل شيء في الكون يغني، فلماذا لا تغني أنت؟", author: "ميخائيل نعيمة" },  
{ text: "السعادة ليست في الوصول، بل في السير نحو القمة.", author: "ميخائيل نعيمة" },  
{ text: "لا شيء يولد عظيماً، العظمة تُكتسب بالعزم.", author: "ميخائيل نعيمة" },  
{ text: "الحب هو اللغة الوحيدة التي يفهمها كل البشر بلا ترجمة.", author: "مي زيادة" },  
{ text: "الكتابة هي الطريقة التي أتنفس بها، وإلا اختنقت.", author: "مي زيادة" },  
{ text: "المرأة التي تقرأ هي امرأة تستعد لقيادة العالم.", author: "مي زيادة" },  
{ text: "لا تحزن إذا خذلك أحد، فالحزن لا يعيد من رحل.", author: "مي زيادة" },  
{ text: "الوحدة ليست فراغًا، بل هي ملكوت الروح.", author: "مي زيادة" },  
{ text: "قلبي يحدثني بأني ميت، وأني غير ميت!", author: "إيليا أبو ماضي" },  
{ text: "ما أبعد الغاية إلا على من لا يريد السير!", author: "إيليا أبو ماضي" },  
{ text: "أنا لا أشتاق إلى وطنٍ، بل أشتاق إلى زمنٍ كان فيه وطني.", author: "إيليا أبو ماضي" },  
{ text: "الحب ليس حبًا إذا كان مشروطًا.", author: "إيليا أبو ماضي" },  
{ text: "كل شيء يموت، إلا الأمل.", author: "إيليا أبو ماضي" },  
{ text: "الحقيقة مثل الشمس، لا يمكنك حجبها بيديك.", author: "أمين الريحاني" },  
{ text: "الحرية لا تُعطى، بل تُؤخذ.", author: "أمين الريحاني" },  
{ text: "الوطن ليس أرضًا، بل ضمير.", author: "أمين الريحاني" },  
{ text: "الكتاب هو الصديق الذي لا يخون.", author: "أمين الريحاني" },  
{ text: "لا تبحث عن السعادة، بل اصنعها.", author: "أمين الريحاني" },  
{ text: "الحب لا يملك شيئًا، ولا يريد أن يُملَك.", author: "مجهول (على نهج جبران)" },  
{ text: "الليل ليس سوى ظل النهار، والحزن ليس سوى ظل الفرح.", author: "مجهول (على نهج جبران)" },  
{ text: "الروح لا تعرف حدودًا، فكيف تحبسها في جسد؟", author: "مجهول (على نهج جبران)" },  
{ text: "الزمن لا يمر، نحن من نمر فيه.", author: "مجهول (على نهج جبران)" },  
{ text: "كل دموعك ستصبح ندىً يُحيي زهرةً في حديقة الله.", author: "مجهول (على نهج جبران)" },  
  ],
}

// Track recent quotes to avoid repetition
const recentQuotes: { [key: string]: Quote[] } = {}
const MAX_RECENT_QUOTES = 30 // Increased to track more recent quotes

export async function getRandomQuote(language: string): Promise<Quote> {
  const languageQuotes = quotes[language] || quotes.en

  // Initialize recent quotes for language if not exists
  if (!recentQuotes[language]) {
    recentQuotes[language] = []
  }

  // Filter out recently shown quotes
  const availableQuotes = languageQuotes.filter(
    (quote) => !recentQuotes[language].some((recent) => recent.text === quote.text && recent.author === quote.author),
  )

  // If all quotes have been shown recently, reset the recent list
  const quotesToChooseFrom = availableQuotes.length > 0 ? availableQuotes : languageQuotes

  // Select random quote
  const randomIndex = Math.floor(Math.random() * quotesToChooseFrom.length)
  const selectedQuote = quotesToChooseFrom[randomIndex]

  // Add to recent quotes
  recentQuotes[language].push(selectedQuote)

  // Keep only the last MAX_RECENT_QUOTES
  if (recentQuotes[language].length > MAX_RECENT_QUOTES) {
    recentQuotes[language] = recentQuotes[language].slice(-MAX_RECENT_QUOTES)
  }

  // Reset recent quotes if we used all available quotes (and there are more than MAX_RECENT_QUOTES total)
  // This ensures we don't get stuck if the total quotes are less than MAX_RECENT_QUOTES
  if (availableQuotes.length === 0 && languageQuotes.length > MAX_RECENT_QUOTES) {
    recentQuotes[language] = [selectedQuote]
  } else if (availableQuotes.length === 0 && languageQuotes.length <= MAX_RECENT_QUOTES) {
    // If total quotes are less than or equal to MAX_RECENT_QUOTES, just reset to the current one
    recentQuotes[language] = [selectedQuote]
  }

  return selectedQuote
}
